export const activitySports = [
  { "26bd": "soccer ball" },
  { "1f3c0": "basketball and hoop" },
  { "1f3c8": "american football" },
  { "26be": "baseball" },
  { "1f3be": "tennis racquet and ball" },
  { "1f3d0": "volleyball" },
  { "1f3c9": "rugby football" },
  { "1f3b1": "billiards" },
  { "26f3": "flag in hole" },
  { "1f3cc": "golfer" },
  { "1f3d3": "table tennis paddle and ball" },
  { "1f3f8": "badminton racquet" },
  { "1f3d2": "ice hockey stick and puck" },
  { "1f3d1": "field hockey stick and ball" },
  { "1f3cf": "cricket bat and ball" },
  { "1f3bf": "ski and ski boot" },
  { "26f7": "skier" },
  { "1f3c2": "snowboarder" },
  { "26f8": "ice skate" },
  { "1f3f9": "bow and arrow" },
  { "1f3a3": "fishing pole and fish" },
  { "1f6a3": "rowboat" },
  { "1f3ca": "swimmer" },
  { "1f3c4": "surfer" },
  { "1f6c0": "bath" },
  { "26f9": "person with ball" },
  { "1f3cb": "weight lifter" },
  { "1f6b4": "bicyclist" },
  { "1f6b5": "mountain bicyclist" },
  { "1f3c7": "horse racing" },
  { "1f574": "man in business suit levitating" },
  { "1f3c6": "trophy" },
  { "1f3bd": "running shirt with sash" },
  { "1f3c5": "sports medal" },
  { "1f396": "military medal" },
  { "1f397": "reminder ribbon" },
  { "1f3f5": "rosette" },
  { "1f3ab": "ticket" },
  { "1f39f": "admission tickets" },
  { "1f3ad": "performing arts" },
  { "1f3a8": "artist palette" },
  { "1f3aa": "circus tent" },
  { "1f3a4": "microphone" },
  { "1f3a7": "headphone" },
  { "1f3bc": "musical score" },
  { "1f3b9": "musical keyboard" },
  { "1f3b7": "saxophone" },
  { "1f3ba": "trumpet" },
  { "1f3b8": "guitar" },
  { "1f3bb": "violin" },
  { "1f3ac": "clapper board" },
  { "1f3ae": "video game" },
  { "1f47e": "alien monster" },
  { "1f3af": "direct hit" },
  { "1f3b2": "game die" },
  { "1f3b0": "slot machine" },
  { "1f3b3": "bowling" }
];
