export const peopleFaces = [
  { "1f600": "grinning face" },
  { "1f62c": "grimacing face" },
  { "1f601": "grinning face with smiling eyes" },
  { "1f602": "face with tears of joy" },
  { "1f603": "smiling face with open mouth" },
  { "1f604": "smiling face with open mouth and smiling eyes" },
  { "1f605": "smiling face with open mouth and cold sweat" },
  { "1f606": "smiling face with open mouth and tightly-closed eyes" },
  { "1f607": "smiling face with halo" },
  { "1f609": "winking face" },
  { "1f60a": "smiling face with smiling eyes" },
  { "1f642": "slightly smiling face" },
  { "263a": "white smiling face" },
  { "1f60b": "face savouring delicious food" },
  { "1f60c": "relieved face" },
  { "1f60d": "smiling face with heart-shaped eyes" },
  { "1f618": "face throwing a kiss" },
  { "1f617": "kissing face" },
  { "1f619": "kissing face with smiling eyes" },
  { "1f61a": "kissing face with closed eyes" },
  { "1f61c": "face with stuck-out tongue and winking eye" },
  { "1f61d": "face with stuck-out tongue and tightly-closed eyes" },
  { "1f61b": "face with stuck-out tongue" },
  { "1f60e": "smiling face with sunglasses" },
  { "1f60f": "smirking face" },
  { "1f636": "face without mouth" },
  { "1f610": "neutral face" },
  { "1f611": "expressionless face" },
  { "1f612": "unamused face" },
  { "1f633": "flushed face" },
  { "1f61e": "disappointed face" },
  { "1f61f": "worried face" },
  { "1f620": "angry face" },
  { "1f621": "pouting face" },
  { "1f614": "pensive face" },
  { "1f615": "confused face" },
  { "1f641": "slightly frowning face" },
  { "2639": "white frowning face" },
  { "1f623": "persevering face" },
  { "1f616": "confounded face" },
  { "1f62b": "tired face" },
  { "1f629": "weary face" },
  { "1f624": "face with look of triumph" },
  { "1f62e": "face with open mouth" },
  { "1f631": "face screaming in fear" },
  { "1f628": "fearful face" },
  { "1f630": "face with open mouth and cold sweat" },
  { "1f62f": "hushed face" },
  { "1f626": "frowning face with open mouth" },
  { "1f627": "anguished face" },
  { "1f622": "crying face" },
  { "1f625": "disappointed but relieved face" },
  { "1f62a": "sleepy face" },
  { "1f613": "face with cold sweat" },
  { "1f62d": "loudly crying face" },
  { "1f635": "dizzy face" },
  { "1f632": "astonished face" },
  { "1f637": "face with medical mask" },
  { "1f634": "sleeping face" },
  { "1f4a4": "sleeping symbol" },
  { "1f4a9": "pile of poo" },
  { "1f608": "smiling face with horns" },
  { "1f47f": "imp" },
  { "1f479": "japanese ogre" },
  { "1f47a": "japanese goblin" },
  { "1f480": "skull" },
  { "1f47b": "ghost" },
  { "1f47d": "extraterrestrial alien" },
  { "1f63a": "smiling cat face with open mouth" },
  { "1f638": "grinning cat face with smiling eyes" },
  { "1f639": "cat face with tears of joy" },
  { "1f63b": "smiling cat face with heart-shaped eyes" },
  { "1f63c": "cat face with wry smile" },
  { "1f63d": "kissing cat face with closed eyes" },
  { "1f640": "weary cat face" },
  { "1f63f": "crying cat face" },
  { "1f63e": "pouting cat face" },
  { "1f64c": "person raising both hands in celebration" },
  { "1f44f": "clapping hands sign" },
  { "1f44b": "waving hand sign" },
  { "1f44d": "thumbs up sign" },
  { "1f44e": "thumbs down sign" },
  { "1f44a": "fisted hand sign" },
  { "270a": "raised fist" },
  { "270c": "victory hand" },
  { "1f44c": "ok hand sign" },
  { "270b": "raised hand" },
  { "1f450": "open hands sign" },
  { "1f4aa": "flexed biceps" },
  { "1f64f": "person with folded hands" },
  { "261d": "white up pointing index" },
  { "1f446": "white up pointing backhand index" },
  { "1f447": "white down pointing backhand index" },
  { "1f448": "white left pointing backhand index" },
  { "1f449": "white right pointing backhand index" },
  { "1f595": "reversed hand with middle finger extended" },
  { "1f590": "raised hand with fingers splayed" },
  { "1f596": "raised hand with part between middle and ring fingers" },
  { "270d": "writing hand" },
  { "1f485": "nail polish" },
  { "1f444": "mouth" },
  { "1f445": "tongue" },
  { "1f442": "ear" },
  { "1f443": "nose" },
  { "1f441": "eye" },
  { "1f440": "eyes" },
  { "1f464": "bust in silhouette" },
  { "1f465": "busts in silhouette" },
  { "1f5e3": "speaking head in silhouette" },
  { "1f476": "baby" },
  { "1f466": "boy" },
  { "1f467": "girl" },
  { "1f468": "man" },
  { "1f469": "woman" },
  { "1f471": "person with blond hair" },
  { "1f474": "older man" },
  { "1f475": "older woman" },
  { "1f472": "man with gua pi mao" },
  { "1f473": "man with turban" },
  { "1f46e": "police officer" },
  { "1f477": "construction worker" },
  { "1f482": "guardsman" },
  { "1f575": "sleuth or spy" },
  { "1f385": "father christmas" },
  { "1f47c": "baby angel" },
  { "1f478": "princess" },
  { "1f470": "bride with veil" },
  { "1f6b6": "pedestrian" },
  { "1f3c3": "runner" },
  { "1f483": "dancer" },
  { "1f46f": "woman with bunny ears" },
  { "1f46b": "man and woman holding hands" },
  { "1f46c": "two men holding hands" },
  { "1f46d": "two women holding hands" },
  { "1f647": "person bowing deeply" },
  { "1f481": "information desk person" },
  { "1f645": "face with no good gesture" },
  { "1f646": "face with ok gesture" },
  { "1f64b": "happy person raising one hand" },
  { "1f64e": "person with pouting face" },
  { "1f64d": "person frowning" },
  { "1f487": "haircut" },
  { "1f486": "face massage" },
  { "1f491": "couple with heart" },
  { "1f48f": "kiss" },
  { "1f46a": "family" },
  { "1f45a": "womans clothes" },
  { "1f455": "t-shirt" },
  { "1f456": "jeans" },
  { "1f454": "necktie" },
  { "1f457": "dress" },
  { "1f459": "bikini" },
  { "1f458": "kimono" },
  { "1f484": "lipstick" },
  { "1f48b": "kiss mark" },
  { "1f463": "footprints" },
  { "1f460": "high-heeled shoe" },
  { "1f461": "womans sandal" },
  { "1f462": "womans boots" },
  { "1f45e": "mans shoe" },
  { "1f45f": "athletic shoe" },
  { "1f452": "womans hat" },
  { "1f3a9": "top hat" },
  { "26d1": "helmet with white cross" },
  { "1f393": "graduation cap" },
  { "1f451": "crown" },
  { "1f392": "school satchel" },
  { "1f45d": "pouch" },
  { "1f45b": "purse" },
  { "1f45c": "handbag" },
  { "1f4bc": "briefcase" },
  { "1f453": "eyeglasses" },
  { "1f576": "dark sunglasses" },
  { "1f48d": "ring" },
  { "1f302": "closed umbrella" }
];
