export const activitySports = [
  { unicode: "26bd", label: "soccer ball" },
  { unicode: "1f3c0", label: "basketball and hoop" },
  { unicode: "1f3c8", label: "american football" },
  { unicode: "26be", label: "baseball" },
  { unicode: "1f3be", label: "tennis racquet and ball" },
  { unicode: "1f3d0", label: "volleyball" },
  { unicode: "1f3c9", label: "rugby football" },
  { unicode: "1f3b1", label: "billiards" },
  { unicode: "26f3", label: "flag in hole" },
  { unicode: "1f3cc", label: "golfer" },
  { unicode: "1f3d3", label: "table tennis paddle and ball" },
  { unicode: "1f3f8", label: "badminton racquet" },
  { unicode: "1f3d2", label: "ice hockey stick and puck" },
  { unicode: "1f3d1", label: "field hockey stick and ball" },
  { unicode: "1f3cf", label: "cricket bat and ball" },
  { unicode: "1f3bf", label: "ski and ski boot" },
  { unicode: "26f7", label: "skier" },
  { unicode: "1f3c2", label: "snowboarder" },
  { unicode: "26f8", label: "ice skate" },
  { unicode: "1f3f9", label: "bow and arrow" },
  { unicode: "1f3a3", label: "fishing pole and fish" },
  { unicode: "1f6a3", label: "rowboat" },
  { unicode: "1f3ca", label: "swimmer" },
  { unicode: "1f3c4", label: "surfer" },
  { unicode: "1f6c0", label: "bath" },
  { unicode: "26f9", label: "person with ball" },
  { unicode: "1f3cb", label: "weight lifter" },
  { unicode: "1f6b4", label: "bicyclist" },
  { unicode: "1f6b5", label: "mountain bicyclist" },
  { unicode: "1f3c7", label: "horse racing" },
  { unicode: "1f574", label: "man in business suit levitating" },
  { unicode: "1f3c6", label: "trophy" },
  { unicode: "1f3bd", label: "running shirt with sash" },
  { unicode: "1f3c5", label: "sports medal" },
  { unicode: "1f396", label: "military medal" },
  { unicode: "1f397", label: "reminder ribbon" },
  { unicode: "1f3f5", label: "rosette" },
  { unicode: "1f3ab", label: "ticket" },
  { unicode: "1f39f", label: "admission tickets" },
  { unicode: "1f3ad", label: "performing arts" },
  { unicode: "1f3a8", label: "artist palette" },
  { unicode: "1f3aa", label: "circus tent" },
  { unicode: "1f3a4", label: "microphone" },
  { unicode: "1f3a7", label: "headphone" },
  { unicode: "1f3bc", label: "musical score" },
  { unicode: "1f3b9", label: "musical keyboard" },
  { unicode: "1f3b7", label: "saxophone" },
  { unicode: "1f3ba", label: "trumpet" },
  { unicode: "1f3b8", label: "guitar" },
  { unicode: "1f3bb", label: "violin" },
  { unicode: "1f3ac", label: "clapper board" },
  { unicode: "1f3ae", label: "video game" },
  { unicode: "1f47e", label: "alien monster" },
  { unicode: "1f3af", label: "direct hit" },
  { unicode: "1f3b2", label: "game die" },
  { unicode: "1f3b0", label: "slot machine" },
  { unicode: "1f3b3", label: "bowling" }
];
