export const allEmojis = [
  //peoplesFaces
  { unicode: "1f600", label: "grinning face" },
  { unicode: "1f62c", label: "grimacing face" },
  { unicode: "1f601", label: "grinning face with smiling eyes" },
  { unicode: "1f602", label: "face with tears of joy" },
  { unicode: "1f603", label: "smiling face with open mouth" },
  { unicode: "1f604", label: "smiling face with open mouth and smiling eyes" },
  { unicode: "1f605", label: "smiling face with open mouth and cold sweat" },
  { unicode: "1f606",label: "smiling face with open mouth and tightly-closed eyes" },
  { unicode: "1f607", label: "smiling face with halo" },
  { unicode: "1f609", label: "winking face" },
  { unicode: "1f60a", label: "smiling face with smiling eyes" },
  { unicode: "1f642", label: "slightly smiling face" },
  { unicode: "263a", label: "white smiling face" },
  { unicode: "1f60b", label: "face savouring delicious food" },
  { unicode: "1f60c", label: "relieved face" },
  { unicode: "1f60d", label: "smiling face with heart-shaped eyes" },
  { unicode: "1f618", label: "face throwing a kiss" },
  { unicode: "1f617", label: "kissing face" },
  { unicode: "1f619", label: "kissing face with smiling eyes" },
  { unicode: "1f61a", label: "kissing face with closed eyes" },
  { unicode: "1f61c", label: "face with stuck-out tongue and winking eye" },
  { unicode: "1f61d", label: "face with stuck-out tongue and tightly-closed eyes" },
  { unicode: "1f61b", label: "face with stuck-out tongue" },
  { unicode: "1f60e", label: "smiling face with sunglasses" },
  { unicode: "1f60f", label: "smirking face" },
  { unicode: "1f636", label: "face without mouth" },
  { unicode: "1f610", label: "neutral face" },
  { unicode: "1f611", label: "expressionless face" },
  { unicode: "1f612", label: "unamused face" },
  { unicode: "1f633", label: "flushed face" },
  { unicode: "1f61e", label: "disappointed face" },
  { unicode: "1f61f", label: "worried face" },
  { unicode: "1f620", label: "angry face" },
  { unicode: "1f621", label: "pouting face" },
  { unicode: "1f614", label: "pensive face" },
  { unicode: "1f615", label: "confused face" },
  { unicode: "1f641", label: "slightly frowning face" },
  { unicode: "2639", label: "white frowning face" },
  { unicode: "1f623", label: "persevering face" },
  { unicode: "1f616", label: "confounded face" },
  { unicode: "1f62b", label: "tired face" },
  { unicode: "1f629", label: "weary face" },
  { unicode: "1f624", label: "face with look of triumph" },
  { unicode: "1f62e", label: "face with open mouth" },
  { unicode: "1f631", label: "face screaming in fear" },
  { unicode: "1f628", label: "fearful face" },
  { unicode: "1f630", label: "face with open mouth and cold sweat" },
  { unicode: "1f62f", label: "hushed face" },
  { unicode: "1f626", label: "frowning face with open mouth" },
  { unicode: "1f627", label: "anguished face" },
  { unicode: "1f622", label: "crying face" },
  { unicode: "1f625", label: "disappointed but relieved face" },
  { unicode: "1f62a", label: "sleepy face" },
  { unicode: "1f613", label: "face with cold sweat" },
  { unicode: "1f62d", label: "loudly crying face" },
  { unicode: "1f635", label: "dizzy face" },
  { unicode: "1f632", label: "astonished face" },
  { unicode: "1f637", label: "face with medical mask" },
  { unicode: "1f634", label: "sleeping face" },
  { unicode: "1f4a4", label: "sleeping symbol" },
  { unicode: "1f4a9", label: "pile of poo" },
  { unicode: "1f608", label: "smiling face with horns" },
  { unicode: "1f47f", label: "imp" },
  { unicode: "1f479", label: "japanese ogre" },
  { unicode: "1f47a", label: "japanese goblin" },
  { unicode: "1f480", label: "skull" },
  { unicode: "1f47b", label: "ghost" },
  { unicode: "1f47d", label: "extraterrestrial alien" },
  { unicode: "1f63a", label: "smiling cat face with open mouth" },
  { unicode: "1f638", label: "grinning cat face with smiling eyes" },
  { unicode: "1f639", label: "cat face with tears of joy" },
  { unicode: "1f63b", label: "smiling cat face with heart-shaped eyes" },
  { unicode: "1f63c", label: "cat face with wry smile" },
  { unicode: "1f63d", label: "kissing cat face with closed eyes" },
  { unicode: "1f640", label: "weary cat face" },
  { unicode: "1f63f", label: "crying cat face" },
  { unicode: "1f63e", label: "pouting cat face" },
  { unicode: "1f64c", label: "person raising both hands in celebration" },
  { unicode: "1f44f", label: "clapping hands sign" },
  { unicode: "1f44b", label: "waving hand sign" },
  { unicode: "1f44d", label: "thumbs up sign" },
  { unicode: "1f44e", label: "thumbs down sign" },
  { unicode: "1f44a", label: "fisted hand sign" },
  { unicode: "270a", label: "raised fist" },
  { unicode: "270c", label: "victory hand" },
  { unicode: "1f44c", label: "ok hand sign" },
  { unicode: "270b", label: "raised hand" },
  { unicode: "1f450", label: "open hands sign" },
  { unicode: "1f4aa", label: "flexed biceps" },
  { unicode: "1f64f", label: "person with folded hands" },
  { unicode: "261d", label: "white up pointing index" },
  { unicode: "1f446", label: "white up pointing backhand index" },
  { unicode: "1f447", label: "white down pointing backhand index" },
  { unicode: "1f448", label: "white left pointing backhand index" },
  { unicode: "1f449", label: "white right pointing backhand index" },
  { unicode: "1f595", label: "reversed hand with middle finger extended" },
  { unicode: "1f590", label: "raised hand with fingers splayed" },
  { unicode: "1f596", label: "raised hand with part between middle and ring fingers" },
  { unicode: "270d", label: "writing hand" },
  { unicode: "1f485", label: "nail polish" },
  { unicode: "1f444", label: "mouth" },
  { unicode: "1f445", label: "tongue" },
  { unicode: "1f442", label: "ear" },
  { unicode: "1f443", label: "nose" },
  { unicode: "1f441", label: "eye" },
  { unicode: "1f440", label: "eyes" },
  { unicode: "1f464", label: "bust in silhouette" },
  { unicode: "1f465", label: "busts in silhouette" },
  { unicode: "1f5e3", label: "speaking head in silhouette" },
  { unicode: "1f476", label: "baby" },
  { unicode: "1f466", label: "boy" },
  { unicode: "1f467", label: "girl" },
  { unicode: "1f468", label: "man" },
  { unicode: "1f469", label: "woman" },
  { unicode: "1f471", label: "person with blond hair" },
  { unicode: "1f474", label: "older man" },
  { unicode: "1f475", label: "older woman" },
  { unicode: "1f472", label: "man with gua pi mao" },
  { unicode: "1f473", label: "man with turban" },
  { unicode: "1f46e", label: "police officer" },
  { unicode: "1f477", label: "construction worker" },
  { unicode: "1f482", label: "guardsman" },
  { unicode: "1f575", label: "sleuth or spy" },
  { unicode: "1f385", label: "father christmas" },
  { unicode: "1f47c", label: "baby angel" },
  { unicode: "1f478", label: "princess" },
  { unicode: "1f470", label: "bride with veil" },
  { unicode: "1f6b6", label: "pedestrian" },
  { unicode: "1f3c3", label: "runner" },
  { unicode: "1f483", label: "dancer" },
  { unicode: "1f46f", label: "woman with bunny ears" },
  { unicode: "1f46b", label: "man and woman holding hands" },
  { unicode: "1f46c", label: "two men holding hands" },
  { unicode: "1f46d", label: "two women holding hands" },
  { unicode: "1f647", label: "person bowing deeply" },
  { unicode: "1f481", label: "information desk person" },
  { unicode: "1f645", label: "face with no good gesture" },
  { unicode: "1f646", label: "face with ok gesture" },
  { unicode: "1f64b", label: "happy person raising one hand" },
  { unicode: "1f64e", label: "person with pouting face" },
  { unicode: "1f64d", label: "person frowning" },
  { unicode: "1f487", label: "haircut" },
  { unicode: "1f486", label: "face massage" },
  { unicode: "1f491", label: "couple with heart" },
  { unicode: "1f48f", label: "kiss" },
  { unicode: "1f46a", label: "family" },
  { unicode: "1f45a", label: "womans clothes" },
  { unicode: "1f455", label: "t-shirt" },
  { unicode: "1f456", label: "jeans" },
  { unicode: "1f454", label: "necktie" },
  { unicode: "1f457", label: "dress" },
  { unicode: "1f459", label: "bikini" },
  { unicode: "1f458", label: "kimono" },
  { unicode: "1f484", label: "lipstick" },
  { unicode: "1f48b", label: "kiss mark" },
  { unicode: "1f463", label: "footprints" },
  { unicode: "1f460", label: "high-heeled shoe" },
  { unicode: "1f461", label: "womans sandal" },
  { unicode: "1f462", label: "womans boots" },
  { unicode: "1f45e", label: "mans shoe" },
  { unicode: "1f45f", label: "athletic shoe" },
  { unicode: "1f452", label: "womans hat" },
  { unicode: "1f3a9", label: "top hat" },
  { unicode: "26d1", label: "helmet with white cross" },
  { unicode: "1f393", label: "graduation cap" },
  { unicode: "1f451", label: "crown" },
  { unicode: "1f392", label: "school satchel" },
  { unicode: "1f45d", label: "pouch" },
  { unicode: "1f45b", label: "purse" },
  { unicode: "1f45c", label: "handbag" },
  { unicode: "1f4bc", label: "briefcase" },
  { unicode: "1f453", label: "eyeglasses" },
  { unicode: "1f576", label: "dark sunglasses" },
  { unicode: "1f48d", label: "ring" },
  { unicode: "1f302", label: "closed umbrella" },
  //animalsNature
  { unicode: "1f436", label: "dog face" },
  { unicode: "1f431", label: "cat face" },
  { unicode: "1f42d", label: "mouse face" },
  { unicode: "1f439", label: "hamster face" },
  { unicode: "1f430", label: "rabbit face" },
  { unicode: "1f43b", label: "bear face" },
  { unicode: "1f43c", label: "panda face" },
  { unicode: "1f428", label: "koala" },
  { unicode: "1f42f", label: "tiger face" },
  { unicode: "1f42e", label: "cow face" },
  { unicode: "1f437", label: "pig face" },
  { unicode: "1f43d", label: "pig nose" },
  { unicode: "1f438", label: "frog face" },
  { unicode: "1f419", label: "octopus" },
  { unicode: "1f435", label: "monkey face" },
  { unicode: "1f648", label: "see-no-evil monkey" },
  { unicode: "1f649", label: "hear-no-evil monkey" },
  { unicode: "1f64a", label: "speak-no-evil monkey" },
  { unicode: "1f412", label: "monkey" },
  { unicode: "1f414", label: "chicken" },
  { unicode: "1f427", label: "penguin" },
  { unicode: "1f426", label: "bird" },
  { unicode: "1f424", label: "baby chick" },
  { unicode: "1f423", label: "hatching chick" },
  { unicode: "1f425", label: "front-facing baby chick" },
  { unicode: "1f43a", label: "wolf face" },
  { unicode: "1f417", label: "boar" },
  { unicode: "1f434", label: "horse face" },
  { unicode: "1f41d", label: "honeybee" },
  { unicode: "1f41b", label: "bug" },
  { unicode: "1f40c", label: "snail" },
  { unicode: "1f41e", label: "lady beetle" },
  { unicode: "1f41c", label: "ant" },
  { unicode: "1f577", label: "spider" },
  { unicode: "1f40d", label: "snake" },
  { unicode: "1f422", label: "turtle" },
  { unicode: "1f420", label: "tropical fish" },
  { unicode: "1f41f", label: "fish" },
  { unicode: "1f421", label: "blowfish" },
  { unicode: "1f42c", label: "dolphin" },
  { unicode: "1f433", label: "spouting whale" },
  { unicode: "1f40b", label: "whale" },
  { unicode: "1f40a", label: "crocodile" },
  { unicode: "1f406", label: "leopard" },
  { unicode: "1f405", label: "tiger" },
  { unicode: "1f403", label: "water buffalo" },
  { unicode: "1f402", label: "ox" },
  { unicode: "1f404", label: "cow" },
  { unicode: "1f42a", label: "dromedary camel" },
  { unicode: "1f42b", label: "bactrian camel" },
  { unicode: "1f418", label: "elephant" },
  { unicode: "1f410", label: "goat" },
  { unicode: "1f40f", label: "ram" },
  { unicode: "1f411", label: "sheep" },
  { unicode: "1f40e", label: "horse" },
  { unicode: "1f416", label: "pig" },
  { unicode: "1f400", label: "rat" },
  { unicode: "1f401", label: "mouse" },
  { unicode: "1f413", label: "rooster" },
  { unicode: "1f54a", label: "dove of peace" },
  { unicode: "1f415", label: "dog" },
  { unicode: "1f429", label: "poodle" },
  { unicode: "1f408", label: "cat" },
  { unicode: "1f407", label: "rabbit" },
  { unicode: "1f43f", label: "chipmunk" },
  { unicode: "1f43e", label: "paw prints" },
  { unicode: "1f409", label: "dragon" },
  { unicode: "1f432", label: "dragon face" },
  { unicode: "1f335", label: "cactus" },
  { unicode: "1f384", label: "christmas tree" },
  { unicode: "1f332", label: "evergreen tree" },
  { unicode: "1f333", label: "deciduous tree" },
  { unicode: "1f334", label: "palm tree" },
  { unicode: "1f331", label: "seedling" },
  { unicode: "1f33f", label: "herb" },
  { unicode: "2618", label: "shamrock" },
  { unicode: "1f340", label: "four leaf clover" },
  { unicode: "1f38d", label: "pine decoration" },
  { unicode: "1f38b", label: "tanabata tree" },
  { unicode: "1f343", label: "leaf fluttering in wind" },
  { unicode: "1f342", label: "fallen leaf" },
  { unicode: "1f341", label: "maple leaf" },
  { unicode: "1f33e", label: "ear of rice" },
  { unicode: "1f33a", label: "hibiscus" },
  { unicode: "1f33b", label: "sunflower" },
  { unicode: "1f339", label: "rose" },
  { unicode: "1f337", label: "tulip" },
  { unicode: "1f33c", label: "blossom" },
  { unicode: "1f338", label: "cherry blossom" },
  { unicode: "1f490", label: "bouquet" },
  { unicode: "1f344", label: "mushroom" },
  { unicode: "1f330", label: "chestnut" },
  { unicode: "1f383", label: "jack-o-lantern" },
  { unicode: "1f41a", label: "spiral shell" },
  { unicode: "1f578", label: "spider web" },
  { unicode: "1f30e", label: "earth globe americas" },
  { unicode: "1f30d", label: "earth globe europe-africa" },
  { unicode: "1f30f", label: "earth globe asia-australia" },
  { unicode: "1f315", label: "full moon symbol" },
  { unicode: "1f316", label: "waning gibbous moon symbol" },
  { unicode: "1f317", label: "last quarter moon symbol" },
  { unicode: "1f318", label: "waning crescent moon symbol" },
  { unicode: "1f311", label: "new moon symbol" },
  { unicode: "1f312", label: "waxing crescent moon symbol" },
  { unicode: "1f313", label: "first quarter moon symbol" },
  { unicode: "1f314", label: "waxing gibbous moon symbol" },
  { unicode: "1f31a", label: "new moon with face" },
  { unicode: "1f31d", label: "full moon with face" },
  { unicode: "1f31b", label: "first quarter moon with face" },
  { unicode: "1f31c", label: "last quarter moon with face" },
  { unicode: "1f31e", label: "sun with face" },
  { unicode: "1f319", label: "crescent moon" },
  { unicode: "2b50", label: "white medium star" },
  { unicode: "1f31f", label: "glowing star" },
  { unicode: "1f4ab", label: "dizzy symbol" },
  { unicode: "2728", label: "sparkles" },
  { unicode: "2604", label: "comet" },
  { unicode: "2600", label: "black sun with rays" },
  { unicode: "1f324", label: "white sun with small cloud" },
  { unicode: "26c5", label: "sun behind cloud" },
  { unicode: "1f325", label: "white sun behind cloud" },
  { unicode: "1f326", label: "white sun behind cloud with rain" },
  { unicode: "2601", label: "cloud" },
  { unicode: "1f327", label: "cloud with rain" },
  { unicode: "26c8", label: "thunder cloud and rain" },
  { unicode: "1f329", label: "cloud with lightning" },
  { unicode: "26a1", label: "high voltage sign" },
  { unicode: "1f525", label: "fire" },
  { unicode: "1f4a5", label: "collision symbol" },
  { unicode: "2744", label: "snowflake" },
  { unicode: "1f328", label: "cloud with snow" },
  { unicode: "2603", label: "snowman" },
  { unicode: "26c4", label: "snowman without snow" },
  { unicode: "1f32c", label: "wind blowing face" },
  { unicode: "1f4a8", label: "dash symbol" },
  { unicode: "1f32a", label: "cloud with tornado" },
  { unicode: "1f32b", label: "fog" },
  { unicode: "2602", label: "umbrella" },
  { unicode: "2614", label: "umbrella with rain drops" },
  { unicode: "1f4a7", label: "droplet" },
  { unicode: "1f4a6", label: "splashing sweat symbol" },
  { unicode: "1f30a", label: "water wave" },
  //foodDrink
  { unicode: "1f34f", label: "green apple" },
  { unicode: "1f34e", label: "red apple" },
  { unicode: "1f350", label: "pear" },
  { unicode: "1f34a", label: "tangerine" },
  { unicode: "1f34b", label: "lemon" },
  { unicode: "1f34c", label: "banana" },
  { unicode: "1f349", label: "watermelon" },
  { unicode: "1f347", label: "grapes" },
  { unicode: "1f353", label: "strawberry" },
  { unicode: "1f348", label: "melon" },
  { unicode: "1f352", label: "cherries" },
  { unicode: "1f351", label: "peach" },
  { unicode: "1f34d", label: "pineapple" },
  { unicode: "1f345", label: "tomato" },
  { unicode: "1f346", label: "aubergine" },
  { unicode: "1f336", label: "hot pepper" },
  { unicode: "1f33d", label: "ear of maize" },
  { unicode: "1f360", label: "roasted sweet potato" },
  { unicode: "1f36f", label: "honey pot" },
  { unicode: "1f35e", label: "bread" },
  { unicode: "1f9c0", label: "cheese wedge" },
  { unicode: "1f357", label: "poultry leg" },
  { unicode: "1f356", label: "meat on bone" },
  { unicode: "1f364", label: "fried shrimp" },
  { unicode: "1f373", label: "cooking" },
  { unicode: "1f354", label: "hamburger" },
  { unicode: "1f35f", label: "french fries" },
  { unicode: "1f32d", label: "hot dog" },
  { unicode: "1f355", label: "slice of pizza" },
  { unicode: "1f35d", label: "spaghetti" },
  { unicode: "1f32e", label: "taco" },
  { unicode: "1f32f", label: "burrito" },
  { unicode: "1f35c", label: "steaming bowl" },
  { unicode: "1f372", label: "pot of food" },
  { unicode: "1f365", label: "fish cake with swirl design" },
  { unicode: "1f363", label: "sushi" },
  { unicode: "1f371", label: "bento box" },
  { unicode: "1f35b", label: "curry and rice" },
  { unicode: "1f359", label: "rice ball" },
  { unicode: "1f35a", label: "cooked rice" },
  { unicode: "1f358", label: "rice cracker" },
  { unicode: "1f362", label: "oden" },
  { unicode: "1f361", label: "dango" },
  { unicode: "1f367", label: "shaved ice" },
  { unicode: "1f368", label: "ice cream" },
  { unicode: "1f366", label: "soft ice cream" },
  { unicode: "1f370", label: "shortcake" },
  { unicode: "1f382", label: "birthday cake" },
  { unicode: "1f36e", label: "custard" },
  { unicode: "1f36c", label: "candy" },
  { unicode: "1f36d", label: "lollipop" },
  { unicode: "1f36b", label: "chocolate bar" },
  { unicode: "1f37f", label: "popcorn" },
  { unicode: "1f369", label: "doughnut" },
  { unicode: "1f36a", label: "cookie" },
  { unicode: "1f37a", label: "beer mug" },
  { unicode: "1f37b", label: "clinking beer mugs" },
  { unicode: "1f377", label: "wine glass" },
  { unicode: "1f378", label: "cocktail glass" },
  { unicode: "1f379", label: "tropical drink" },
  { unicode: "1f37e", label: "bottle with popping cork" },
  { unicode: "1f376", label: "sake bottle and cup" },
  { unicode: "1f375", label: "teacup without handle" },
  { unicode: "2615", label: "hot beverage" },
  { unicode: "1f37c", label: "baby bottle" },
  { unicode: "1f374", label: "fork and knife" },
  { unicode: "1f37d", label: "fork and knife with plate" },
  //activitySports
  { unicode: "26bd", label: "soccer ball" },
  { unicode: "1f3c0", label: "basketball and hoop" },
  { unicode: "1f3c8", label: "american football" },
  { unicode: "26be", label: "baseball" },
  { unicode: "1f3be", label: "tennis racquet and ball" },
  { unicode: "1f3d0", label: "volleyball" },
  { unicode: "1f3c9", label: "rugby football" },
  { unicode: "1f3b1", label: "billiards" },
  { unicode: "26f3", label: "flag in hole" },
  { unicode: "1f3cc", label: "golfer" },
  { unicode: "1f3d3", label: "table tennis paddle and ball" },
  { unicode: "1f3f8", label: "badminton racquet" },
  { unicode: "1f3d2", label: "ice hockey stick and puck" },
  { unicode: "1f3d1", label: "field hockey stick and ball" },
  { unicode: "1f3cf", label: "cricket bat and ball" },
  { unicode: "1f3bf", label: "ski and ski boot" },
  { unicode: "26f7", label: "skier" },
  { unicode: "1f3c2", label: "snowboarder" },
  { unicode: "26f8", label: "ice skate" },
  { unicode: "1f3f9", label: "bow and arrow" },
  { unicode: "1f3a3", label: "fishing pole and fish" },
  { unicode: "1f6a3", label: "rowboat" },
  { unicode: "1f3ca", label: "swimmer" },
  { unicode: "1f3c4", label: "surfer" },
  { unicode: "1f6c0", label: "bath" },
  { unicode: "26f9", label: "person with ball" },
  { unicode: "1f3cb", label: "weight lifter" },
  { unicode: "1f6b4", label: "bicyclist" },
  { unicode: "1f6b5", label: "mountain bicyclist" },
  { unicode: "1f3c7", label: "horse racing" },
  { unicode: "1f574", label: "man in business suit levitating" },
  { unicode: "1f3c6", label: "trophy" },
  { unicode: "1f3bd", label: "running shirt with sash" },
  { unicode: "1f3c5", label: "sports medal" },
  { unicode: "1f396", label: "military medal" },
  { unicode: "1f397", label: "reminder ribbon" },
  { unicode: "1f3f5", label: "rosette" },
  { unicode: "1f3ab", label: "ticket" },
  { unicode: "1f39f", label: "admission tickets" },
  { unicode: "1f3ad", label: "performing arts" },
  { unicode: "1f3a8", label: "artist palette" },
  { unicode: "1f3aa", label: "circus tent" },
  { unicode: "1f3a4", label: "microphone" },
  { unicode: "1f3a7", label: "headphone" },
  { unicode: "1f3bc", label: "musical score" },
  { unicode: "1f3b9", label: "musical keyboard" },
  { unicode: "1f3b7", label: "saxophone" },
  { unicode: "1f3ba", label: "trumpet" },
  { unicode: "1f3b8", label: "guitar" },
  { unicode: "1f3bb", label: "violin" },
  { unicode: "1f3ac", label: "clapper board" },
  { unicode: "1f3ae", label: "video game" },
  { unicode: "1f47e", label: "alien monster" },
  { unicode: "1f3af", label: "direct hit" },
  { unicode: "1f3b2", label: "game die" },
  { unicode: "1f3b0", label: "slot machine" },
  { unicode: "1f3b3", label: "bowling" },
  //travelPlaces
  { unicode: "1f697", label: "automobile" },
  { unicode: "1f695", label: "taxi" },
  { unicode: "1f699", label: "recreational vehicle" },
  { unicode: "1f68c", label: "bus" },
  { unicode: "1f68e", label: "trolleybus" },
  { unicode: "1f3ce", label: "racing car" },
  { unicode: "1f693", label: "police car" },
  { unicode: "1f691", label: "ambulance" },
  { unicode: "1f692", label: "fire engine" },
  { unicode: "1f690", label: "minibus" },
  { unicode: "1f69a", label: "delivery truck" },
  { unicode: "1f69b", label: "articulated lorry" },
  { unicode: "1f69c", label: "tractor" },
  { unicode: "1f3cd", label: "racing motorcycle" },
  { unicode: "1f6b2", label: "bicycle" },
  { unicode: "1f6a8", label: "police cars revolving light" },
  { unicode: "1f694", label: "oncoming police car" },
  { unicode: "1f68d", label: "oncoming bus" },
  { unicode: "1f698", label: "oncoming automobile" },
  { unicode: "1f696", label: "oncoming taxi" },
  { unicode: "1f6a1", label: "aerial tramway" },
  { unicode: "1f6a0", label: "mountain cableway" },
  { unicode: "1f69f", label: "suspension railway" },
  { unicode: "1f683", label: "railway car" },
  { unicode: "1f68b", label: "tram car" },
  { unicode: "1f69d", label: "monorail" },
  { unicode: "1f684", label: "high-speed train" },
  { unicode: "1f685", label: "high-speed train with bullet nose" },
  { unicode: "1f688", label: "light rail" },
  { unicode: "1f69e", label: "mountain railway" },
  { unicode: "1f682", label: "steam locomotive" },
  { unicode: "1f686", label: "train" },
  { unicode: "1f687", label: "metro" },
  { unicode: "1f68a", label: "tram" },
  { unicode: "1f689", label: "station" },
  { unicode: "1f681", label: "helicopter" },
  { unicode: "1f6e9", label: "small airplane" },
  { unicode: "2708", label: "airplane" },
  { unicode: "1f6eb", label: "airplane departure" },
  { unicode: "1f6ec", label: "airplane arriving" },
  { unicode: "26f5", label: "sailboat" },
  { unicode: "1f6e5", label: "motorboat" },
  { unicode: "1f6a4", label: "speedboat" },
  { unicode: "26f4", label: "ferry" },
  { unicode: "1f6f3", label: "passenger ship" },
  { unicode: "1f680", label: "rocket" },
  { unicode: "1f6f0", label: "satellite" },
  { unicode: "1f4ba", label: "seat" },
  { unicode: "2693", label: "anchor" },
  { unicode: "1f6a7", label: "construction sign" },
  { unicode: "26fd", label: "fuel pump" },
  { unicode: "1f68f", label: "bus stop" },
  { unicode: "1f6a6", label: "vertical traffic light" },
  { unicode: "1f6a5", label: "horizontal traffic light" },
  { unicode: "1f3c1", label: "chequered flag" },
  { unicode: "1f6a2", label: "ship" },
  { unicode: "1f3a1", label: "ferris wheel" },
  { unicode: "1f3a2", label: "roller coaster" },
  { unicode: "1f3a0", label: "carousel horse" },
  { unicode: "1f3d7", label: "building construction" },
  { unicode: "1f301", label: "foggy" },
  { unicode: "1f5fc", label: "tokyo tower" },
  { unicode: "1f3ed", label: "factory" },
  { unicode: "26f2", label: "fountain" },
  { unicode: "1f391", label: "moon viewing ceremony" },
  { unicode: "26f0", label: "mountain" },
  { unicode: "1f3d4", label: "snow capped mountain" },
  { unicode: "1f5fb", label: "mount fuji" },
  { unicode: "1f30b", label: "volcano" },
  { unicode: "1f5fe", label: "silhouette of japan" },
  { unicode: "1f3d5", label: "camping" },
  { unicode: "26fa", label: "tent" },
  { unicode: "1f3de", label: "national park" },
  { unicode: "1f6e3", label: "motorway" },
  { unicode: "1f6e4", label: "railway track" },
  { unicode: "1f305", label: "sunrise" },
  { unicode: "1f304", label: "sunrise over mountains" },
  { unicode: "1f3dc", label: "desert" },
  { unicode: "1f3d6", label: "beach with umbrella" },
  { unicode: "1f3dd", label: "desert island" },
  { unicode: "1f307", label: "sunset over buildings" },
  { unicode: "1f306", label: "cityscape at dusk" },
  { unicode: "1f3d9", label: "cityscape" },
  { unicode: "1f303", label: "night with stars" },
  { unicode: "1f309", label: "bridge at night" },
  { unicode: "1f30c", label: "milky way" },
  { unicode: "1f320", label: "shooting star" },
  { unicode: "1f387", label: "firework sparkler" },
  { unicode: "1f386", label: "fireworks" },
  { unicode: "1f308", label: "rainbow" },
  { unicode: "1f3d8", label: "house buildings" },
  { unicode: "1f3f0", label: "european castle" },
  { unicode: "1f3ef", label: "japanese castle" },
  { unicode: "1f3df", label: "stadium" },
  { unicode: "1f5fd", label: "statue of liberty" },
  { unicode: "1f3e0", label: "house building" },
  { unicode: "1f3e1", label: "house with garden" },
  { unicode: "1f3da", label: "derelict house building" },
  { unicode: "1f3e2", label: "office building" },
  { unicode: "1f3ec", label: "department store" },
  { unicode: "1f3e3", label: "japanese post office" },
  { unicode: "1f3e4", label: "european post office" },
  { unicode: "1f3e5", label: "hospital" },
  { unicode: "1f3e6", label: "bank" },
  { unicode: "1f3e8", label: "hotel" },
  { unicode: "1f3ea", label: "convenience store" },
  { unicode: "1f3eb", label: "school" },
  { unicode: "1f3e9", label: "love hotel" },
  { unicode: "1f492", label: "wedding" },
  { unicode: "1f3db", label: "classical building" },
  { unicode: "26ea", label: "church" },
  { unicode: "1f54c", label: "mosque" },
  { unicode: "1f54d", label: "synagogue" },
  { unicode: "1f54b", label: "kaaba" },
  { unicode: "26e9", label: "shinto shrine" },
  //objectsMedia
  { unicode: "231a", label: "watch" },
  { unicode: "1f4f1", label: "mobile phone" },
  { unicode: "1f4f2", label: "mobile phone with rightwards arrow at left" },
  { unicode: "1f4bb", label: "personal computer" },
  { unicode: "2328", label: "keyboard" },
  { unicode: "1f5a5", label: "desktop computer" },
  { unicode: "1f5a8", label: "printer" },
  { unicode: "1f5b1", label: "three button mouse" },
  { unicode: "1f5b2", label: "trackball" },
  { unicode: "1f579", label: "joystick" },
  { unicode: "1f5dc", label: "compression" },
  { unicode: "1f4bd", label: "minidisc" },
  { unicode: "1f4be", label: "floppy disk" },
  { unicode: "1f4bf", label: "optical disc" },
  { unicode: "1f4c0", label: "dvd" },
  { unicode: "1f4fc", label: "videocassette" },
  { unicode: "1f4f7", label: "camera" },
  { unicode: "1f4f8", label: "camera with flash" },
  { unicode: "1f4f9", label: "video camera" },
  { unicode: "1f3a5", label: "movie camera" },
  { unicode: "1f4fd", label: "film projector" },
  { unicode: "1f39e", label: "film frames" },
  { unicode: "1f4de", label: "telephone receiver" },
  { unicode: "260e", label: "black telephone" },
  { unicode: "1f4df", label: "pager" },
  { unicode: "1f4e0", label: "fax machine" },
  { unicode: "1f4fa", label: "television" },
  { unicode: "1f4fb", label: "radio" },
  { unicode: "1f399", label: "studio microphone" },
  { unicode: "1f39a", label: "level slider" },
  { unicode: "1f39b", label: "control knobs" },
  { unicode: "23f1", label: "stopwatch" },
  { unicode: "23f2", label: "timer clock" },
  { unicode: "23f0", label: "alarm clock" },
  { unicode: "1f570", label: "mantlepiece clock" },
  { unicode: "23f3", label: "hourglass with flowing sand" },
  { unicode: "231b", label: "hourglass" },
  { unicode: "1f4e1", label: "satellite antenna" },
  { unicode: "1f50b", label: "battery" },
  { unicode: "1f50c", label: "electric plug" },
  { unicode: "1f4a1", label: "electric light bulb" },
  { unicode: "1f526", label: "electric torch" },
  { unicode: "1f56f", label: "candle" },
  { unicode: "1f5d1", label: "wastebasket" },
  { unicode: "1f6e2", label: "oil drum" },
  { unicode: "1f4b8", label: "money with wings" },
  { unicode: "1f4b5", label: "banknote with dollar sign" },
  { unicode: "1f4b4", label: "banknote with yen sign" },
  { unicode: "1f4b6", label: "banknote with euro sign" },
  { unicode: "1f4b7", label: "banknote with pound sign" },
  { unicode: "1f4b0", label: "money bag" },
  { unicode: "1f4b3", label: "credit card" },
  { unicode: "1f48e", label: "gem stone" },
  { unicode: "2696", label: "scales" },
  { unicode: "1f527", label: "wrench" },
  { unicode: "1f528", label: "hammer" },
  { unicode: "2692", label: "hammer and pick" },
  { unicode: "1f6e0", label: "hammer and wrench" },
  { unicode: "26cf", label: "pick" },
  { unicode: "1f529", label: "nut and bolt" },
  { unicode: "2699", label: "gear" },
  { unicode: "26d3", label: "chains" },
  { unicode: "1f52b", label: "pistol" },
  { unicode: "1f4a3", label: "bomb" },
  { unicode: "1f52a", label: "hocho" },
  { unicode: "1f5e1", label: "dagger knife" },
  { unicode: "2694", label: "crossed swords" },
  { unicode: "1f6e1", label: "shield" },
  { unicode: "1f6ac", label: "smoking symbol" },
  { unicode: "2620", label: "skull and crossbones" },
  { unicode: "26b0", label: "coffin" },
  { unicode: "26b1", label: "funeral urn" },
  { unicode: "1f3fa", label: "amphora" },
  { unicode: "1f52e", label: "crystal ball" },
  { unicode: "1f4ff", label: "prayer beads" },
  { unicode: "1f488", label: "barber pole" },
  { unicode: "2697", label: "alembic" },
  { unicode: "1f52d", label: "telescope" },
  { unicode: "1f52c", label: "microscope" },
  { unicode: "1f573", label: "hole" },
  { unicode: "1f48a", label: "pill" },
  { unicode: "1f489", label: "syringe" },
  { unicode: "1f321", label: "thermometer" },
  { unicode: "1f3f7", label: "label" },
  { unicode: "1f516", label: "bookmark" },
  { unicode: "1f6bd", label: "toilet" },
  { unicode: "1f6bf", label: "shower" },
  { unicode: "1f6c1", label: "bathtub" },
  { unicode: "1f511", label: "key" },
  { unicode: "1f5dd", label: "old key" },
  { unicode: "1f6cb", label: "couch and lamp" },
  { unicode: "1f6cc", label: "sleeping accommodation" },
  { unicode: "1f6cf", label: "bed" },
  { unicode: "1f6aa", label: "door" },
  { unicode: "1f6ce", label: "bellhop bell" },
  { unicode: "1f5bc", label: "frame with picture" },
  { unicode: "1f5fa", label: "world map" },
  { unicode: "26f1", label: "umbrella on ground" },
  { unicode: "1f5ff", label: "moyai" },
  { unicode: "1f6cd", label: "shopping bags" },
  { unicode: "1f388", label: "balloon" },
  { unicode: "1f38f", label: "carp streamer" },
  { unicode: "1f380", label: "ribbon" },
  { unicode: "1f381", label: "wrapped present" },
  { unicode: "1f38a", label: "confetti ball" },
  { unicode: "1f389", label: "party popper" },
  { unicode: "1f38e", label: "japanese dolls" },
  { unicode: "1f390", label: "wind chime" },
  { unicode: "1f38c", label: "crossed flags" },
  { unicode: "1f3ee", label: "izakaya lantern" },
  { unicode: "2709", label: "envelope" },
  { unicode: "1f4e9", label: "envelope with downwards arrow above" },
  { unicode: "1f4e8", label: "incoming envelope" },
  { unicode: "1f4e7", label: "e-mail symbol" },
  { unicode: "1f48c", label: "love letter" },
  { unicode: "1f4ee", label: "postbox" },
  { unicode: "1f4ea", label: "closed mailbox with lowered flag" },
  { unicode: "1f4eb", label: "closed mailbox with raised flag" },
  { unicode: "1f4ec", label: "open mailbox with raised flag" },
  { unicode: "1f4ed", label: "open mailbox with lowered flag" },
  { unicode: "1f4e6", label: "package" },
  { unicode: "1f4ef", label: "postal horn" },
  { unicode: "1f4e5", label: "inbox tray" },
  { unicode: "1f4e4", label: "outbox tray" },
  { unicode: "1f4dc", label: "scroll" },
  { unicode: "1f4c3", label: "page with curl" },
  { unicode: "1f4d1", label: "bookmark tabs" },
  { unicode: "1f4ca", label: "bar chart" },
  { unicode: "1f4c8", label: "chart with upwards trend" },
  { unicode: "1f4c9", label: "chart with downwards trend" },
  { unicode: "1f4c4", label: "page facing up" },
  { unicode: "1f4c5", label: "calendar" },
  { unicode: "1f4c6", label: "tear-off calendar" },
  { unicode: "1f5d3", label: "spiral calendar pad" },
  { unicode: "1f4c7", label: "card index" },
  { unicode: "1f5c3", label: "card file box" },
  { unicode: "1f5f3", label: "ballot box with ballot" },
  { unicode: "1f5c4", label: "file cabinet" },
  { unicode: "1f4cb", label: "clipboard" },
  { unicode: "1f5d2", label: "spiral note pad" },
  { unicode: "1f4c1", label: "file folder" },
  { unicode: "1f4c2", label: "open file folder" },
  { unicode: "1f5c2", label: "card index dividers" },
  { unicode: "1f5de", label: "rolled-up newspaper" },
  { unicode: "1f4f0", label: "newspaper" },
  { unicode: "1f4d3", label: "notebook" },
  { unicode: "1f4d5", label: "closed book" },
  { unicode: "1f4d7", label: "green book" },
  { unicode: "1f4d8", label: "blue book" },
  { unicode: "1f4d9", label: "orange book" },
  { unicode: "1f4d4", label: "notebook with decorative cover" },
  { unicode: "1f4d2", label: "ledger" },
  { unicode: "1f4da", label: "books" },
  { unicode: "1f4d6", label: "open book" },
  { unicode: "1f517", label: "link symbol" },
  { unicode: "1f4ce", label: "paperclip" },
  { unicode: "1f587", label: "linked paperclips" },
  { unicode: "2702", label: "black scissors" },
  { unicode: "1f4d0", label: "triangular ruler" },
  { unicode: "1f4cf", label: "straight ruler" },
  { unicode: "1f4cc", label: "pushpin" },
  { unicode: "1f4cd", label: "round pushpin" },
  { unicode: "1f6a9", label: "triangular flag on post" },
  { unicode: "1f3f3", label: "waving white flag" },
  { unicode: "1f3f4", label: "waving black flag" },
  { unicode: "1f510", label: "closed lock with key" },
  { unicode: "1f512", label: "lock" },
  { unicode: "1f513", label: "open lock" },
  { unicode: "1f50f", label: "lock with ink pen" },
  { unicode: "1f58a", label: "lower left ballpoint pen" },
  { unicode: "1f58b", label: "lower left fountain pen" },
  { unicode: "2712", label: "black nib" },
  { unicode: "1f4dd", label: "memo" },
  { unicode: "270f", label: "pencil" },
  { unicode: "1f58d", label: "lower left crayon" },
  { unicode: "1f58c", label: "lower left paintbrush" },
  { unicode: "1f50d", label: "left-pointing magnifying glass" },
  { unicode: "1f50e", label: "right-pointing magnifying glass" },
  //symbols
  { unicode: "2764", label: "heavy black heart" },
  { unicode: "1f49b", label: "yellow heart" },
  { unicode: "1f49a", label: "green heart" },
  { unicode: "1f499", label: "blue heart" },
  { unicode: "1f49c", label: "purple heart" },
  { unicode: "1f494", label: "broken heart" },
  { unicode: "2763", label: "heavy heart exclamation mark ornament" },
  { unicode: "1f495", label: "two hearts" },
  { unicode: "1f49e", label: "revolving hearts" },
  { unicode: "1f493", label: "beating heart" },
  { unicode: "1f497", label: "growing heart" },
  { unicode: "1f496", label: "sparkling heart" },
  { unicode: "1f498", label: "heart with arrow" },
  { unicode: "1f49d", label: "heart with ribbon" },
  { unicode: "1f49f", label: "heart decoration" },
  { unicode: "262e", label: "peace symbol" },
  { unicode: "271d", label: "latin cross" },
  { unicode: "262a", label: "star and crescent" },
  { unicode: "1f549", label: "om symbol" },
  { unicode: "2638", label: "wheel of dharma" },
  { unicode: "2721", label: "star of david" },
  { unicode: "1f52f", label: "six pointed star with middle dot" },
  { unicode: "1f54e", label: "menorah with nine branches" },
  { unicode: "262f", label: "yin yang" },
  { unicode: "2626", label: "orthodox cross" },
  { unicode: "1f6d0", label: "place of worship" },
  { unicode: "26ce", label: "ophiuchus" },
  { unicode: "2648", label: "aries" },
  { unicode: "2649", label: "taurus" },
  { unicode: "264a", label: "gemini" },
  { unicode: "264b", label: "cancer" },
  { unicode: "264c", label: "leo" },
  { unicode: "264d", label: "virgo" },
  { unicode: "264e", label: "libra" },
  { unicode: "264f", label: "scorpius" },
  { unicode: "2650", label: "sagittarius" },
  { unicode: "2651", label: "capricorn" },
  { unicode: "2652", label: "aquarius" },
  { unicode: "2653", label: "pisces" },
  { unicode: "1f194", label: "squared id" },
  { unicode: "269b", label: "atom symbol" },
  { unicode: "1f233", label: "squared cjk unified ideograph-7a7a" },
  { unicode: "1f239", label: "squared cjk unified ideograph-5272" },
  { unicode: "2622", label: "radioactive sign" },
  { unicode: "2623", label: "biohazard sign" },
  { unicode: "1f4f4", label: "mobile phone off" },
  { unicode: "1f4f3", label: "vibration mode" },
  { unicode: "1f236", label: "squared cjk unified ideograph-6709" },
  { unicode: "1f21a", label: "squared cjk unified ideograph-7121" },
  { unicode: "1f238", label: "squared cjk unified ideograph-7533" },
  { unicode: "1f23a", label: "squared cjk unified ideograph-55b6" },
  { unicode: "1f237", label: "squared cjk unified ideograph-6708" },
  { unicode: "2734", label: "eight pointed black star" },
  { unicode: "1f19a", label: "squared vs" },
  { unicode: "1f251", label: "circled ideograph accept" },
  { unicode: "1f4ae", label: "white flower" },
  { unicode: "1f250", label: "circled ideograph advantage" },
  { unicode: "3299", label: "circled ideograph secret" },
  { unicode: "3297", label: "circled ideograph congratulation" },
  { unicode: "1f234", label: "squared cjk unified ideograph-5408" },
  { unicode: "1f235", label: "squared cjk unified ideograph-6e80" },
  { unicode: "1f232", label: "squared cjk unified ideograph-7981" },
  { unicode: "1f170", label: "negative squared latin capital letter a" },
  { unicode: "1f171", label: "negative squared latin capital letter b" },
  { unicode: "1f18e", label: "negative squared ab" },
  { unicode: "1f191", label: "squared cl" },
  { unicode: "1f17e", label: "negative squared latin capital letter o" },
  { unicode: "1f198", label: "squared sos" },
  { unicode: "26d4", label: "no entry" },
  { unicode: "1f4db", label: "name badge" },
  { unicode: "1f6ab", label: "no entry sign" },
  { unicode: "274c", label: "cross mark" },
  { unicode: "2b55", label: "heavy large circle" },
  { unicode: "1f4a2", label: "anger symbol" },
  { unicode: "2668", label: "hot springs" },
  { unicode: "1f6b7", label: "no pedestrians" },
  { unicode: "1f6af", label: "do not litter symbol" },
  { unicode: "1f6b3", label: "no bicycles" },
  { unicode: "1f6b1", label: "non-potable water symbol" },
  { unicode: "1f51e", label: "no one under eighteen symbol" },
  { unicode: "1f4f5", label: "no mobile phones" },
  { unicode: "2757", label: "heavy exclamation mark symbol" },
  { unicode: "2755", label: "white exclamation mark ornament" },
  { unicode: "2753", label: "black question mark ornament" },
  { unicode: "2754", label: "white question mark ornament" },
  { unicode: "203c", label: "double exclamation mark" },
  { unicode: "2049", label: "exclamation question mark" },
  { unicode: "1f4af", label: "hundred points symbol" },
  { unicode: "1f505", label: "low brightness symbol" },
  { unicode: "1f506", label: "high brightness symbol" },
  { unicode: "1f531", label: "trident emblem" },
  { unicode: "269c", label: "fleur-de-lis" },
  { unicode: "303d", label: "part alternation mark" },
  { unicode: "26a0", label: "warning sign" },
  { unicode: "1f6b8", label: "children crossing" },
  { unicode: "1f530", label: "japanese symbol for beginner" },
  { unicode: "267b", label: "black universal recycling symbol" },
  { unicode: "1f22f", label: "squared cjk unified ideograph-6307" },
  { unicode: "1f4b9", label: "chart with upwards trend and yen sign" },
  { unicode: "2747", label: "sparkle" },
  { unicode: "2733", label: "eight spoked asterisk" },
  { unicode: "274e", label: "negative squared cross mark" },
  { unicode: "2705", label: "white heavy check mark" },
  { unicode: "1f4a0", label: "diamond shape with a dot inside" },
  { unicode: "1f300", label: "cyclone" },
  { unicode: "27bf", label: "double curly loop" },
  { unicode: "1f310", label: "globe with meridians" },
  { unicode: "24c2", label: "circled latin capital letter m" },
  { unicode: "1f3e7", label: "automated teller machine" },
  { unicode: "1f202", label: "squared katakana sa" },
  { unicode: "1f6c2", label: "passport control" },
  { unicode: "1f6c3", label: "customs" },
  { unicode: "1f6c4", label: "baggage claim" },
  { unicode: "1f6c5", label: "left luggage" },
  { unicode: "267f", label: "wheelchair symbol" },
  { unicode: "1f6ad", label: "no smoking symbol" },
  { unicode: "1f6be", label: "water closet" },
  { unicode: "1f17f", label: "negative squared latin capital letter p" },
  { unicode: "1f6b0", label: "potable water symbol" },
  { unicode: "1f6b9", label: "mens symbol" },
  { unicode: "1f6ba", label: "womens symbol" },
  { unicode: "1f6bc", label: "baby symbol" },
  { unicode: "1f6bb", label: "restroom" },
  { unicode: "1f6ae", label: "put litter in its place symbol" },
  { unicode: "1f3a6", label: "cinema" },
  { unicode: "1f4f6", label: "antenna with bars" },
  { unicode: "1f201", label: "squared katakana koko" },
  { unicode: "1f196", label: "squared ng" },
  { unicode: "1f197", label: "squared ok" },
  { unicode: "1f199", label: "squared up with exclamation mark" },
  { unicode: "1f192", label: "squared cool" },
  { unicode: "1f195", label: "squared new" },
  { unicode: "1f193", label: "squared free" },
  { unicode: "1f51f", label: "keycap ten" },
  { unicode: "1f522", label: "input symbol for numbers" },
  { unicode: "25b6", label: "black right-pointing triangle" },
  { unicode: "23f8", label: "double vertical bar" },
  { unicode: "23ef", label: "black right-pointing double triangle with double vertical bar" },
  { unicode: "23f9", label: "black square for stop" },
  { unicode: "23fa", label: "black circle for record" },
  { unicode: "23ed", label: "black right-pointing double triangle with vertical bar" },
  { unicode: "23ee", label: "black left-pointing double triangle with vertical bar" },
  { unicode: "23e9", label: "black right-pointing double triangle" },
  { unicode: "23ea", label: "black left-pointing double triangle" },
  { unicode: "1f500", label: "twisted rightwards arrows" },
  { unicode: "1f501", label: "clockwise rightwards and leftwards open circle arrows" },
  { unicode: "1f502", label: "clockwise rightwards and leftwards open circle arrows with circled one overlay" },
  { unicode: "25c0", label: "black left-pointing triangle" },
  { unicode: "1f53c", label: "up-pointing small red triangle" },
  { unicode: "1f53d", label: "down-pointing small red triangle" },
  { unicode: "23eb", label: "black up-pointing double triangle" },
  { unicode: "23ec", label: "black down-pointing double triangle" },
  { unicode: "27a1", label: "black rightwards arrow" },
  { unicode: "2b05", label: "leftwards black arrow" },
  { unicode: "2b06", label: "upwards black arrow" },
  { unicode: "2b07", label: "downwards black arrow" },
  { unicode: "2197", label: "north east arrow" },
  { unicode: "2198", label: "south east arrow" },
  { unicode: "2199", label: "south west arrow" },
  { unicode: "2196", label: "north west arrow" },
  { unicode: "2195", label: "up down arrow" },
  { unicode: "2194", label: "left right arrow" },
  { unicode: "1f504", label: "anticlockwise downwards and upwards open circle arrows" },
  { unicode: "21aa", label: "rightwards arrow with hook" },
  { unicode: "21a9", label: "leftwards arrow with hook" },
  { unicode: "2934", label: "arrow pointing rightwards then curving upwards" },
  { unicode: "2935", label: "arrow pointing rightwards then curving downwards" },
  { unicode: "2139", label: "information source" },
  { unicode: "1f524", label: "input symbol for latin letters" },
  { unicode: "1f521", label: "input symbol for latin small letters" },
  { unicode: "1f520", label: "input symbol for latin capital letters" },
  { unicode: "1f523", label: "input symbol for symbols" },
  { unicode: "1f3b5", label: "musical note" },
  { unicode: "1f3b6", label: "multiple musical notes" },
  { unicode: "3030", label: "wavy dash" },
  { unicode: "27b0", label: "curly loop" },
  { unicode: "2714", label: "heavy check mark" },
  { unicode: "1f503", label: "clockwise downwards and upwards open circle arrows" },
  { unicode: "2795", label: "heavy plus sign" },
  { unicode: "2796", label: "heavy minus sign" },
  { unicode: "2797", label: "heavy division sign" },
  { unicode: "2716", label: "heavy multiplication x" },
  { unicode: "1f4b2", label: "heavy dollar sign" },
  { unicode: "1f4b1", label: "currency exchange" },
  { unicode: "a9", label: "copyright sign" },
  { unicode: "ae", label: "registered sign" },
  { unicode: "2122", label: "trade mark sign" },
  { unicode: "1f51a", label: "end with leftwards arrow above" },
  { unicode: "1f519", label: "back with leftwards arrow above" },
  { unicode: "1f51b", label: "on with exclamation mark with left right arrow above" },
  { unicode: "1f51d", label: "top with upwards arrow above" },
  { unicode: "1f51c", label: "soon with rightwards arrow above" },
  { unicode: "2611", label: "ballot box with check" },
  { unicode: "1f518", label: "radio button" },
  { unicode: "26aa", label: "medium white circle" },
  { unicode: "26ab", label: "medium black circle" },
  { unicode: "1f534", label: "large red circle" },
  { unicode: "1f535", label: "large blue circle" },
  { unicode: "1f538", label: "small orange diamond" },
  { unicode: "1f539", label: "small blue diamond" },
  { unicode: "1f536", label: "large orange diamond" },
  { unicode: "1f537", label: "large blue diamond" },
  { unicode: "1f53a", label: "up-pointing red triangle" },
  { unicode: "25aa", label: "black small square" },
  { unicode: "25ab", label: "white small square" },
  { unicode: "2b1b", label: "black large square" },
  { unicode: "2b1c", label: "white large square" },
  { unicode: "1f53b", label: "down-pointing red triangle" },
  { unicode: "25fc", label: "black medium square" },
  { unicode: "25fb", label: "white medium square" },
  { unicode: "25fe", label: "black medium small square" },
  { unicode: "25fd", label: "white medium small square" },
  { unicode: "1f532", label: "black square button" },
  { unicode: "1f533", label: "white square button" },
  { unicode: "1f508", label: "speaker" },
  { unicode: "1f509", label: "speaker with one sound wave" },
  { unicode: "1f50a", label: "speaker with three sound waves" },
  { unicode: "1f507", label: "speaker with cancellation stroke" },
  { unicode: "1f4e3", label: "cheering megaphone" },
  { unicode: "1f4e2", label: "public address loudspeaker" },
  { unicode: "1f514", label: "bell" },
  { unicode: "1f515", label: "bell with cancellation stroke" },
  { unicode: "1f0cf", label: "playing card black joker" },
  { unicode: "1f004", label: "mahjong tile red dragon" },
  { unicode: "2660", label: "black spade suit" },
  { unicode: "2663", label: "black club suit" },
  { unicode: "2665", label: "black heart suit" },
  { unicode: "2666", label: "black diamond suit" },
  { unicode: "1f3b4", label: "flower playing cards" },
  { unicode: "1f4ad", label: "thought balloon" },
  { unicode: "1f5ef", label: "right anger bubble" },
  { unicode: "1f4ac", label: "speech balloon" },
  { unicode: "1f550", label: "clock face one oclock" },
  { unicode: "1f551", label: "clock face two oclock" },
  { unicode: "1f552", label: "clock face three oclock" },
  { unicode: "1f553", label: "clock face four oclock" },
  { unicode: "1f554", label: "clock face five oclock" },
  { unicode: "1f555", label: "clock face six oclock" },
  { unicode: "1f556", label: "clock face seven oclock" },
  { unicode: "1f557", label: "clock face eight oclock" },
  { unicode: "1f558", label: "clock face nine oclock" },
  { unicode: "1f559", label: "clock face ten oclock" },
  { unicode: "1f55a", label: "clock face eleven oclock" },
  { unicode: "1f55b", label: "clock face twelve oclock" },
  { unicode: "1f55c", label: "clock face one-thirty" },
  { unicode: "1f55d", label: "clock face two-thirty" },
  { unicode: "1f55e", label: "clock face three-thirty" },
  { unicode: "1f55f", label: "clock face four-thirty" },
  { unicode: "1f560", label: "clock face five-thirty" },
  { unicode: "1f561", label: "clock face six-thirty" },
  { unicode: "1f562", label: "clock face seven-thirty" },
  { unicode: "1f563", label: "clock face eight-thirty" },
  { unicode: "1f564", label: "clock face nine-thirty" },
  { unicode: "1f565", label: "clock face ten-thirty" },
  { unicode: "1f566", label: "clock face eleven-thirty" },
  { unicode: "1f567", label: "clock face twelve-thirty" }
];
