export const animalsNature = [
  { unicode: "1f436", label: "dog face" },
  { unicode: "1f431", label: "cat face" },
  { unicode: "1f42d", label: "mouse face" },
  { unicode: "1f439", label: "hamster face" },
  { unicode: "1f430", label: "rabbit face" },
  { unicode: "1f43b", label: "bear face" },
  { unicode: "1f43c", label: "panda face" },
  { unicode: "1f428", label: "koala" },
  { unicode: "1f42f", label: "tiger face" },
  { unicode: "1f42e", label: "cow face" },
  { unicode: "1f437", label: "pig face" },
  { unicode: "1f43d", label: "pig nose" },
  { unicode: "1f438", label: "frog face" },
  { unicode: "1f419", label: "octopus" },
  { unicode: "1f435", label: "monkey face" },
  { unicode: "1f648", label: "see-no-evil monkey" },
  { unicode: "1f649", label: "hear-no-evil monkey" },
  { unicode: "1f64a", label: "speak-no-evil monkey" },
  { unicode: "1f412", label: "monkey" },
  { unicode: "1f414", label: "chicken" },
  { unicode: "1f427", label: "penguin" },
  { unicode: "1f426", label: "bird" },
  { unicode: "1f424", label: "baby chick" },
  { unicode: "1f423", label: "hatching chick" },
  { unicode: "1f425", label: "front-facing baby chick" },
  { unicode: "1f43a", label: "wolf face" },
  { unicode: "1f417", label: "boar" },
  { unicode: "1f434", label: "horse face" },
  { unicode: "1f41d", label: "honeybee" },
  { unicode: "1f41b", label: "bug" },
  { unicode: "1f40c", label: "snail" },
  { unicode: "1f41e", label: "lady beetle" },
  { unicode: "1f41c", label: "ant" },
  { unicode: "1f577", label: "spider" },
  { unicode: "1f40d", label: "snake" },
  { unicode: "1f422", label: "turtle" },
  { unicode: "1f420", label: "tropical fish" },
  { unicode: "1f41f", label: "fish" },
  { unicode: "1f421", label: "blowfish" },
  { unicode: "1f42c", label: "dolphin" },
  { unicode: "1f433", label: "spouting whale" },
  { unicode: "1f40b", label: "whale" },
  { unicode: "1f40a", label: "crocodile" },
  { unicode: "1f406", label: "leopard" },
  { unicode: "1f405", label: "tiger" },
  { unicode: "1f403", label: "water buffalo" },
  { unicode: "1f402", label: "ox" },
  { unicode: "1f404", label: "cow" },
  { unicode: "1f42a", label: "dromedary camel" },
  { unicode: "1f42b", label: "bactrian camel" },
  { unicode: "1f418", label: "elephant" },
  { unicode: "1f410", label: "goat" },
  { unicode: "1f40f", label: "ram" },
  { unicode: "1f411", label: "sheep" },
  { unicode: "1f40e", label: "horse" },
  { unicode: "1f416", label: "pig" },
  { unicode: "1f400", label: "rat" },
  { unicode: "1f401", label: "mouse" },
  { unicode: "1f413", label: "rooster" },
  { unicode: "1f54a", label: "dove of peace" },
  { unicode: "1f415", label: "dog" },
  { unicode: "1f429", label: "poodle" },
  { unicode: "1f408", label: "cat" },
  { unicode: "1f407", label: "rabbit" },
  { unicode: "1f43f", label: "chipmunk" },
  { unicode: "1f43e", label: "paw prints" },
  { unicode: "1f409", label: "dragon" },
  { unicode: "1f432", label: "dragon face" },
  { unicode: "1f335", label: "cactus" },
  { unicode: "1f384", label: "christmas tree" },
  { unicode: "1f332", label: "evergreen tree" },
  { unicode: "1f333", label: "deciduous tree" },
  { unicode: "1f334", label: "palm tree" },
  { unicode: "1f331", label: "seedling" },
  { unicode: "1f33f", label: "herb" },
  { unicode: "2618", label: "shamrock" },
  { unicode: "1f340", label: "four leaf clover" },
  { unicode: "1f38d", label: "pine decoration" },
  { unicode: "1f38b", label: "tanabata tree" },
  { unicode: "1f343", label: "leaf fluttering in wind" },
  { unicode: "1f342", label: "fallen leaf" },
  { unicode: "1f341", label: "maple leaf" },
  { unicode: "1f33e", label: "ear of rice" },
  { unicode: "1f33a", label: "hibiscus" },
  { unicode: "1f33b", label: "sunflower" },
  { unicode: "1f339", label: "rose" },
  { unicode: "1f337", label: "tulip" },
  { unicode: "1f33c", label: "blossom" },
  { unicode: "1f338", label: "cherry blossom" },
  { unicode: "1f490", label: "bouquet" },
  { unicode: "1f344", label: "mushroom" },
  { unicode: "1f330", label: "chestnut" },
  { unicode: "1f383", label: "jack-o-lantern" },
  { unicode: "1f41a", label: "spiral shell" },
  { unicode: "1f578", label: "spider web" },
  { unicode: "1f30e", label: "earth globe americas" },
  { unicode: "1f30d", label: "earth globe europe-africa" },
  { unicode: "1f30f", label: "earth globe asia-australia" },
  { unicode: "1f315", label: "full moon symbol" },
  { unicode: "1f316", label: "waning gibbous moon symbol" },
  { unicode: "1f317", label: "last quarter moon symbol" },
  { unicode: "1f318", label: "waning crescent moon symbol" },
  { unicode: "1f311", label: "new moon symbol" },
  { unicode: "1f312", label: "waxing crescent moon symbol" },
  { unicode: "1f313", label: "first quarter moon symbol" },
  { unicode: "1f314", label: "waxing gibbous moon symbol" },
  { unicode: "1f31a", label: "new moon with face" },
  { unicode: "1f31d", label: "full moon with face" },
  { unicode: "1f31b", label: "first quarter moon with face" },
  { unicode: "1f31c", label: "last quarter moon with face" },
  { unicode: "1f31e", label: "sun with face" },
  { unicode: "1f319", label: "crescent moon" },
  { unicode: "2b50", label: "white medium star" },
  { unicode: "1f31f", label: "glowing star" },
  { unicode: "1f4ab", label: "dizzy symbol" },
  { unicode: "2728", label: "sparkles" },
  { unicode: "2604", label: "comet" },
  { unicode: "2600", label: "black sun with rays" },
  { unicode: "1f324", label: "white sun with small cloud" },
  { unicode: "26c5", label: "sun behind cloud" },
  { unicode: "1f325", label: "white sun behind cloud" },
  { unicode: "1f326", label: "white sun behind cloud with rain" },
  { unicode: "2601", label: "cloud" },
  { unicode: "1f327", label: "cloud with rain" },
  { unicode: "26c8", label: "thunder cloud and rain" },
  { unicode: "1f329", label: "cloud with lightning" },
  { unicode: "26a1", label: "high voltage sign" },
  { unicode: "1f525", label: "fire" },
  { unicode: "1f4a5", label: "collision symbol" },
  { unicode: "2744", label: "snowflake" },
  { unicode: "1f328", label: "cloud with snow" },
  { unicode: "2603", label: "snowman" },
  { unicode: "26c4", label: "snowman without snow" },
  { unicode: "1f32c", label: "wind blowing face" },
  { unicode: "1f4a8", label: "dash symbol" },
  { unicode: "1f32a", label: "cloud with tornado" },
  { unicode: "1f32b", label: "fog" },
  { unicode: "2602", label: "umbrella" },
  { unicode: "2614", label: "umbrella with rain drops" },
  { unicode: "1f4a7", label: "droplet" },
  { unicode: "1f4a6", label: "splashing sweat symbol" },
  { unicode: "1f30a", label: "water wave" }
];
