export const animalsNature = [
  { unicode: "1f436.svg", label: "dog face" },
  { unicode: "1f431.svg", label: "cat face" },
  { unicode: "1f42d.svg", label: "mouse face" },
  { unicode: "1f439.svg", label: "hamster face" },
  { unicode: "1f430.svg", label: "rabbit face" },
  { unicode: "1f43b.svg", label: "bear face" },
  { unicode: "1f43c.svg", label: "panda face" },
  { unicode: "1f428.svg", label: "koala" },
  { unicode: "1f42f.svg", label: "tiger face" },
  { unicode: "1f42e.svg", label: "cow face" },
  { unicode: "1f437.svg", label: "pig face" },
  { unicode: "1f43d.svg", label: "pig nose" },
  { unicode: "1f438.svg", label: "frog face" },
  { unicode: "1f419.svg", label: "octopus" },
  { unicode: "1f435.svg", label: "monkey face" },
  { unicode: "1f648.svg", label: "see-no-evil monkey" },
  { unicode: "1f649.svg", label: "hear-no-evil monkey" },
  { unicode: "1f64a.svg", label: "speak-no-evil monkey" },
  { unicode: "1f412.svg", label: "monkey" },
  { unicode: "1f414.svg", label: "chicken" },
  { unicode: "1f427.svg", label: "penguin" },
  { unicode: "1f426.svg", label: "bird" },
  { unicode: "1f424.svg", label: "baby chick" },
  { unicode: "1f423.svg", label: "hatching chick" },
  { unicode: "1f425.svg", label: "front-facing baby chick" },
  { unicode: "1f43a.svg", label: "wolf face" },
  { unicode: "1f417.svg", label: "boar" },
  { unicode: "1f434.svg", label: "horse face" },
  { unicode: "1f41d.svg", label: "honeybee" },
  { unicode: "1f41b.svg", label: "bug" },
  { unicode: "1f40c.svg", label: "snail" },
  { unicode: "1f41e.svg", label: "lady beetle" },
  { unicode: "1f41c.svg", label: "ant" },
  { unicode: "1f577.svg", label: "spider" },
  { unicode: "1f40d.svg", label: "snake" },
  { unicode: "1f422.svg", label: "turtle" },
  { unicode: "1f420.svg", label: "tropical fish" },
  { unicode: "1f41f.svg", label: "fish" },
  { unicode: "1f421.svg", label: "blowfish" },
  { unicode: "1f42c.svg", label: "dolphin" },
  { unicode: "1f433.svg", label: "spouting whale" },
  { unicode: "1f40b.svg", label: "whale" },
  { unicode: "1f40a.svg", label: "crocodile" },
  { unicode: "1f406.svg", label: "leopard" },
  { unicode: "1f405.svg", label: "tiger" },
  { unicode: "1f403.svg", label: "water buffalo" },
  { unicode: "1f402.svg", label: "ox" },
  { unicode: "1f404.svg", label: "cow" },
  { unicode: "1f42a.svg", label: "dromedary camel" },
  { unicode: "1f42b.svg", label: "bactrian camel" },
  { unicode: "1f418.svg", label: "elephant" },
  { unicode: "1f410.svg", label: "goat" },
  { unicode: "1f40f.svg", label: "ram" },
  { unicode: "1f411.svg", label: "sheep" },
  { unicode: "1f40e.svg", label: "horse" },
  { unicode: "1f416.svg", label: "pig" },
  { unicode: "1f400.svg", label: "rat" },
  { unicode: "1f401.svg", label: "mouse" },
  { unicode: "1f413.svg", label: "rooster" },
  { unicode: "1f54a.svg", label: "dove of peace" },
  { unicode: "1f415.svg", label: "dog" },
  { unicode: "1f429.svg", label: "poodle" },
  { unicode: "1f408.svg", label: "cat" },
  { unicode: "1f407.svg", label: "rabbit" },
  { unicode: "1f43f.svg", label: "chipmunk" },
  { unicode: "1f43e.svg", label: "paw prints" },
  { unicode: "1f409.svg", label: "dragon" },
  { unicode: "1f432.svg", label: "dragon face" },
  { unicode: "1f335.svg", label: "cactus" },
  { unicode: "1f384.svg", label: "christmas tree" },
  { unicode: "1f332.svg", label: "evergreen tree" },
  { unicode: "1f333.svg", label: "deciduous tree" },
  { unicode: "1f334.svg", label: "palm tree" },
  { unicode: "1f331.svg", label: "seedling" },
  { unicode: "1f33f.svg", label: "herb" },
  { unicode: "2618.svg", label: "shamrock" },
  { unicode: "1f340.svg", label: "four leaf clover" },
  { unicode: "1f38d.svg", label: "pine decoration" },
  { unicode: "1f38b.svg", label: "tanabata tree" },
  { unicode: "1f343.svg", label: "leaf fluttering in wind" },
  { unicode: "1f342.svg", label: "fallen leaf" },
  { unicode: "1f341.svg", label: "maple leaf" },
  { unicode: "1f33e.svg", label: "ear of rice" },
  { unicode: "1f33a.svg", label: "hibiscus" },
  { unicode: "1f33b.svg", label: "sunflower" },
  { unicode: "1f339.svg", label: "rose" },
  { unicode: "1f337.svg", label: "tulip" },
  { unicode: "1f33c.svg", label: "blossom" },
  { unicode: "1f338.svg", label: "cherry blossom" },
  { unicode: "1f490.svg", label: "bouquet" },
  { unicode: "1f344.svg", label: "mushroom" },
  { unicode: "1f330.svg", label: "chestnut" },
  { unicode: "1f383.svg", label: "jack-o-lantern" },
  { unicode: "1f41a.svg", label: "spiral shell" },
  { unicode: "1f578.svg", label: "spider web" },
  { unicode: "1f30e.svg", label: "earth globe americas" },
  { unicode: "1f30d.svg", label: "earth globe europe-africa" },
  { unicode: "1f30f.svg", label: "earth globe asia-australia" },
  { unicode: "1f315.svg", label: "full moon symbol" },
  { unicode: "1f316.svg", label: "waning gibbous moon symbol" },
  { unicode: "1f317.svg", label: "last quarter moon symbol" },
  { unicode: "1f318.svg", label: "waning crescent moon symbol" },
  { unicode: "1f311.svg", label: "new moon symbol" },
  { unicode: "1f312.svg", label: "waxing crescent moon symbol" },
  { unicode: "1f313.svg", label: "first quarter moon symbol" },
  { unicode: "1f314.svg", label: "waxing gibbous moon symbol" },
  { unicode: "1f31a.svg", label: "new moon with face" },
  { unicode: "1f31d.svg", label: "full moon with face" },
  { unicode: "1f31b.svg", label: "first quarter moon with face" },
  { unicode: "1f31c.svg", label: "last quarter moon with face" },
  { unicode: "1f31e.svg", label: "sun with face" },
  { unicode: "1f319.svg", label: "crescent moon" },
  { unicode: "2b50.svg", label: "white medium star" },
  { unicode: "1f31f.svg", label: "glowing star" },
  { unicode: "1f4ab.svg", label: "dizzy symbol" },
  { unicode: "2728.svg", label: "sparkles" },
  { unicode: "2604.svg", label: "comet" },
  { unicode: "2600.svg", label: "black sun with rays" },
  { unicode: "1f324.svg", label: "white sun with small cloud" },
  { unicode: "26c5.svg", label: "sun behind cloud" },
  { unicode: "1f325.svg", label: "white sun behind cloud" },
  { unicode: "1f326.svg", label: "white sun behind cloud with rain" },
  { unicode: "2601.svg", label: "cloud" },
  { unicode: "1f327.svg", label: "cloud with rain" },
  { unicode: "26c8.svg", label: "thunder cloud and rain" },
  { unicode: "1f329.svg", label: "cloud with lightning" },
  { unicode: "26a1.svg", label: "high voltage sign" },
  { unicode: "1f525.svg", label: "fire" },
  { unicode: "1f4a5.svg", label: "collision symbol" },
  { unicode: "2744.svg", label: "snowflake" },
  { unicode: "1f328.svg", label: "cloud with snow" },
  { unicode: "2603.svg", label: "snowman" },
  { unicode: "26c4.svg", label: "snowman without snow" },
  { unicode: "1f32c.svg", label: "wind blowing face" },
  { unicode: "1f4a8.svg", label: "dash symbol" },
  { unicode: "1f32a.svg", label: "cloud with tornado" },
  { unicode: "1f32b.svg", label: "fog" },
  { unicode: "2602.svg", label: "umbrella" },
  { unicode: "2614.svg", label: "umbrella with rain drops" },
  { unicode: "1f4a7.svg", label: "droplet" },
  { unicode: "1f4a6.svg", label: "splashing sweat symbol" },
  { unicode: "1f30a.svg", label: "water wave" }
];
