export const foodDrink = [
  { unicode: "1f34f", label: "green apple" },
  { unicode: "1f34e", label: "red apple" },
  { unicode: "1f350", label: "pear" },
  { unicode: "1f34a", label: "tangerine" },
  { unicode: "1f34b", label: "lemon" },
  { unicode: "1f34c", label: "banana" },
  { unicode: "1f349", label: "watermelon" },
  { unicode: "1f347", label: "grapes" },
  { unicode: "1f353", label: "strawberry" },
  { unicode: "1f348", label: "melon" },
  { unicode: "1f352", label: "cherries" },
  { unicode: "1f351", label: "peach" },
  { unicode: "1f34d", label: "pineapple" },
  { unicode: "1f345", label: "tomato" },
  { unicode: "1f346", label: "aubergine" },
  { unicode: "1f336", label: "hot pepper" },
  { unicode: "1f33d", label: "ear of maize" },
  { unicode: "1f360", label: "roasted sweet potato" },
  { unicode: "1f36f", label: "honey pot" },
  { unicode: "1f35e", label: "bread" },
  { unicode: "1f9c0", label: "cheese wedge" },
  { unicode: "1f357", label: "poultry leg" },
  { unicode: "1f356", label: "meat on bone" },
  { unicode: "1f364", label: "fried shrimp" },
  { unicode: "1f373", label: "cooking" },
  { unicode: "1f354", label: "hamburger" },
  { unicode: "1f35f", label: "french fries" },
  { unicode: "1f32d", label: "hot dog" },
  { unicode: "1f355", label: "slice of pizza" },
  { unicode: "1f35d", label: "spaghetti" },
  { unicode: "1f32e", label: "taco" },
  { unicode: "1f32f", label: "burrito" },
  { unicode: "1f35c", label: "steaming bowl" },
  { unicode: "1f372", label: "pot of food" },
  { unicode: "1f365", label: "fish cake with swirl design" },
  { unicode: "1f363", label: "sushi" },
  { unicode: "1f371", label: "bento box" },
  { unicode: "1f35b", label: "curry and rice" },
  { unicode: "1f359", label: "rice ball" },
  { unicode: "1f35a", label: "cooked rice" },
  { unicode: "1f358", label: "rice cracker" },
  { unicode: "1f362", label: "oden" },
  { unicode: "1f361", label: "dango" },
  { unicode: "1f367", label: "shaved ice" },
  { unicode: "1f368", label: "ice cream" },
  { unicode: "1f366", label: "soft ice cream" },
  { unicode: "1f370", label: "shortcake" },
  { unicode: "1f382", label: "birthday cake" },
  { unicode: "1f36e", label: "custard" },
  { unicode: "1f36c", label: "candy" },
  { unicode: "1f36d", label: "lollipop" },
  { unicode: "1f36b", label: "chocolate bar" },
  { unicode: "1f37f", label: "popcorn" },
  { unicode: "1f369", label: "doughnut" },
  { unicode: "1f36a", label: "cookie" },
  { unicode: "1f37a", label: "beer mug" },
  { unicode: "1f37b", label: "clinking beer mugs" },
  { unicode: "1f377", label: "wine glass" },
  { unicode: "1f378", label: "cocktail glass" },
  { unicode: "1f379", label: "tropical drink" },
  { unicode: "1f37e", label: "bottle with popping cork" },
  { unicode: "1f376", label: "sake bottle and cup" },
  { unicode: "1f375", label: "teacup without handle" },
  { unicode: "2615", label: "hot beverage" },
  { unicode: "1f37c", label: "baby bottle" },
  { unicode: "1f374", label: "fork and knife" },
  { unicode: "1f37d", label: "fork and knife with plate" }
];
