export const foodDrink = [
  { unicode: "1f34f.svg", label: "green apple" },
  { unicode: "1f34e.svg", label: "red apple" },
  { unicode: "1f350.svg", label: "pear" },
  { unicode: "1f34a.svg", label: "tangerine" },
  { unicode: "1f34b.svg", label: "lemon" },
  { unicode: "1f34c.svg", label: "banana" },
  { unicode: "1f349.svg", label: "watermelon" },
  { unicode: "1f347.svg", label: "grapes" },
  { unicode: "1f353.svg", label: "strawberry" },
  { unicode: "1f348.svg", label: "melon" },
  { unicode: "1f352.svg", label: "cherries" },
  { unicode: "1f351.svg", label: "peach" },
  { unicode: "1f34d.svg", label: "pineapple" },
  { unicode: "1f345.svg", label: "tomato" },
  { unicode: "1f346.svg", label: "aubergine" },
  { unicode: "1f336.svg", label: "hot pepper" },
  { unicode: "1f33d.svg", label: "ear of maize" },
  { unicode: "1f360.svg", label: "roasted sweet potato" },
  { unicode: "1f36f.svg", label: "honey pot" },
  { unicode: "1f35e.svg", label: "bread" },
  { unicode: "1f9c0.svg", label: "cheese wedge" },
  { unicode: "1f357.svg", label: "poultry leg" },
  { unicode: "1f356.svg", label: "meat on bone" },
  { unicode: "1f364.svg", label: "fried shrimp" },
  { unicode: "1f373.svg", label: "cooking" },
  { unicode: "1f354.svg", label: "hamburger" },
  { unicode: "1f35f.svg", label: "french fries" },
  { unicode: "1f32d.svg", label: "hot dog" },
  { unicode: "1f355.svg", label: "slice of pizza" },
  { unicode: "1f35d.svg", label: "spaghetti" },
  { unicode: "1f32e.svg", label: "taco" },
  { unicode: "1f32f.svg", label: "burrito" },
  { unicode: "1f35c.svg", label: "steaming bowl" },
  { unicode: "1f372.svg", label: "pot of food" },
  { unicode: "1f365.svg", label: "fish cake with swirl design" },
  { unicode: "1f363.svg", label: "sushi" },
  { unicode: "1f371.svg", label: "bento box" },
  { unicode: "1f35b.svg", label: "curry and rice" },
  { unicode: "1f359.svg", label: "rice ball" },
  { unicode: "1f35a.svg", label: "cooked rice" },
  { unicode: "1f358.svg", label: "rice cracker" },
  { unicode: "1f362.svg", label: "oden" },
  { unicode: "1f361.svg", label: "dango" },
  { unicode: "1f367.svg", label: "shaved ice" },
  { unicode: "1f368.svg", label: "ice cream" },
  { unicode: "1f366.svg", label: "soft ice cream" },
  { unicode: "1f370.svg", label: "shortcake" },
  { unicode: "1f382.svg", label: "birthday cake" },
  { unicode: "1f36e.svg", label: "custard" },
  { unicode: "1f36c.svg", label: "candy" },
  { unicode: "1f36d.svg", label: "lollipop" },
  { unicode: "1f36b.svg", label: "chocolate bar" },
  { unicode: "1f37f.svg", label: "popcorn" },
  { unicode: "1f369.svg", label: "doughnut" },
  { unicode: "1f36a.svg", label: "cookie" },
  { unicode: "1f37a.svg", label: "beer mug" },
  { unicode: "1f37b.svg", label: "clinking beer mugs" },
  { unicode: "1f377.svg", label: "wine glass" },
  { unicode: "1f378.svg", label: "cocktail glass" },
  { unicode: "1f379.svg", label: "tropical drink" },
  { unicode: "1f37e.svg", label: "bottle with popping cork" },
  { unicode: "1f376.svg", label: "sake bottle and cup" },
  { unicode: "1f375.svg", label: "teacup without handle" },
  { unicode: "2615.svg", label: "hot beverage" },
  { unicode: "1f37c.svg", label: "baby bottle" },
  { unicode: "1f374.svg", label: "fork and knife" },
  { unicode: "1f37d.svg", label: "fork and knife with plate" }
];
