export const objectsMedia = [
  { "231a": "watch" },
  { "1f4f1": "mobile phone" },
  { "1f4f2": "mobile phone with rightwards arrow at left" },
  { "1f4bb": "personal computer" },
  { "2328": "keyboard" },
  { "1f5a5": "desktop computer" },
  { "1f5a8": "printer" },
  { "1f5b1": "three button mouse" },
  { "1f5b2": "trackball" },
  { "1f579": "joystick" },
  { "1f5dc": "compression" },
  { "1f4bd": "minidisc" },
  { "1f4be": "floppy disk" },
  { "1f4bf": "optical disc" },
  { "1f4c0": "dvd" },
  { "1f4fc": "videocassette" },
  { "1f4f7": "camera" },
  { "1f4f8": "camera with flash" },
  { "1f4f9": "video camera" },
  { "1f3a5": "movie camera" },
  { "1f4fd": "film projector" },
  { "1f39e": "film frames" },
  { "1f4de": "telephone receiver" },
  { "260e": "black telephone" },
  { "1f4df": "pager" },
  { "1f4e0": "fax machine" },
  { "1f4fa": "television" },
  { "1f4fb": "radio" },
  { "1f399": "studio microphone" },
  { "1f39a": "level slider" },
  { "1f39b": "control knobs" },
  { "23f1": "stopwatch" },
  { "23f2": "timer clock" },
  { "23f0": "alarm clock" },
  { "1f570": "mantlepiece clock" },
  { "23f3": "hourglass with flowing sand" },
  { "231b": "hourglass" },
  { "1f4e1": "satellite antenna" },
  { "1f50b": "battery" },
  { "1f50c": "electric plug" },
  { "1f4a1": "electric light bulb" },
  { "1f526": "electric torch" },
  { "1f56f": "candle" },
  { "1f5d1": "wastebasket" },
  { "1f6e2": "oil drum" },
  { "1f4b8": "money with wings" },
  { "1f4b5": "banknote with dollar sign" },
  { "1f4b4": "banknote with yen sign" },
  { "1f4b6": "banknote with euro sign" },
  { "1f4b7": "banknote with pound sign" },
  { "1f4b0": "money bag" },
  { "1f4b3": "credit card" },
  { "1f48e": "gem stone" },
  { "2696": "scales" },
  { "1f527": "wrench" },
  { "1f528": "hammer" },
  { "2692": "hammer and pick" },
  { "1f6e0": "hammer and wrench" },
  { "26cf": "pick" },
  { "1f529": "nut and bolt" },
  { "2699": "gear" },
  { "26d3": "chains" },
  { "1f52b": "pistol" },
  { "1f4a3": "bomb" },
  { "1f52a": "hocho" },
  { "1f5e1": "dagger knife" },
  { "2694": "crossed swords" },
  { "1f6e1": "shield" },
  { "1f6ac": "smoking symbol" },
  { "2620": "skull and crossbones" },
  { "26b0": "coffin" },
  { "26b1": "funeral urn" },
  { "1f3fa": "amphora" },
  { "1f52e": "crystal ball" },
  { "1f4ff": "prayer beads" },
  { "1f488": "barber pole" },
  { "2697": "alembic" },
  { "1f52d": "telescope" },
  { "1f52c": "microscope" },
  { "1f573": "hole" },
  { "1f48a": "pill" },
  { "1f489": "syringe" },
  { "1f321": "thermometer" },
  { "1f3f7": "label" },
  { "1f516": "bookmark" },
  { "1f6bd": "toilet" },
  { "1f6bf": "shower" },
  { "1f6c1": "bathtub" },
  { "1f511": "key" },
  { "1f5dd": "old key" },
  { "1f6cb": "couch and lamp" },
  { "1f6cc": "sleeping accommodation" },
  { "1f6cf": "bed" },
  { "1f6aa": "door" },
  { "1f6ce": "bellhop bell" },
  { "1f5bc": "frame with picture" },
  { "1f5fa": "world map" },
  { "26f1": "umbrella on ground" },
  { "1f5ff": "moyai" },
  { "1f6cd": "shopping bags" },
  { "1f388": "balloon" },
  { "1f38f": "carp streamer" },
  { "1f380": "ribbon" },
  { "1f381": "wrapped present" },
  { "1f38a": "confetti ball" },
  { "1f389": "party popper" },
  { "1f38e": "japanese dolls" },
  { "1f390": "wind chime" },
  { "1f38c": "crossed flags" },
  { "1f3ee": "izakaya lantern" },
  { "2709": "envelope" },
  { "1f4e9": "envelope with downwards arrow above" },
  { "1f4e8": "incoming envelope" },
  { "1f4e7": "e-mail symbol" },
  { "1f48c": "love letter" },
  { "1f4ee": "postbox" },
  { "1f4ea": "closed mailbox with lowered flag" },
  { "1f4eb": "closed mailbox with raised flag" },
  { "1f4ec": "open mailbox with raised flag" },
  { "1f4ed": "open mailbox with lowered flag" },
  { "1f4e6": "package" },
  { "1f4ef": "postal horn" },
  { "1f4e5": "inbox tray" },
  { "1f4e4": "outbox tray" },
  { "1f4dc": "scroll" },
  { "1f4c3": "page with curl" },
  { "1f4d1": "bookmark tabs" },
  { "1f4ca": "bar chart" },
  { "1f4c8": "chart with upwards trend" },
  { "1f4c9": "chart with downwards trend" },
  { "1f4c4": "page facing up" },
  { "1f4c5": "calendar" },
  { "1f4c6": "tear-off calendar" },
  { "1f5d3": "spiral calendar pad" },
  { "1f4c7": "card index" },
  { "1f5c3": "card file box" },
  { "1f5f3": "ballot box with ballot" },
  { "1f5c4": "file cabinet" },
  { "1f4cb": "clipboard" },
  { "1f5d2": "spiral note pad" },
  { "1f4c1": "file folder" },
  { "1f4c2": "open file folder" },
  { "1f5c2": "card index dividers" },
  { "1f5de": "rolled-up newspaper" },
  { "1f4f0": "newspaper" },
  { "1f4d3": "notebook" },
  { "1f4d5": "closed book" },
  { "1f4d7": "green book" },
  { "1f4d8": "blue book" },
  { "1f4d9": "orange book" },
  { "1f4d4": "notebook with decorative cover" },
  { "1f4d2": "ledger" },
  { "1f4da": "books" },
  { "1f4d6": "open book" },
  { "1f517": "link symbol" },
  { "1f4ce": "paperclip" },
  { "1f587": "linked paperclips" },
  { "2702": "black scissors" },
  { "1f4d0": "triangular ruler" },
  { "1f4cf": "straight ruler" },
  { "1f4cc": "pushpin" },
  { "1f4cd": "round pushpin" },
  { "1f6a9": "triangular flag on post" },
  { "1f3f3": "waving white flag" },
  { "1f3f4": "waving black flag" },
  { "1f510": "closed lock with key" },
  { "1f512": "lock" },
  { "1f513": "open lock" },
  { "1f50f": "lock with ink pen" },
  { "1f58a": "lower left ballpoint pen" },
  { "1f58b": "lower left fountain pen" },
  { "2712": "black nib" },
  { "1f4dd": "memo" },
  { "270f": "pencil" },
  { "1f58d": "lower left crayon" },
  { "1f58c": "lower left paintbrush" },
  { "1f50d": "left-pointing magnifying glass" },
  { "1f50e": "right-pointing magnifying glass" }
];
