export const objectsMedia = [
  { unicode: "231a", label: "watch" },
  { unicode: "1f4f1", label: "mobile phone" },
  { unicode: "1f4f2", label: "mobile phone with rightwards arrow at left" },
  { unicode: "1f4bb", label: "personal computer" },
  { unicode: "2328", label: "keyboard" },
  { unicode: "1f5a5", label: "desktop computer" },
  { unicode: "1f5a8", label: "printer" },
  { unicode: "1f5b1", label: "three button mouse" },
  { unicode: "1f5b2", label: "trackball" },
  { unicode: "1f579", label: "joystick" },
  { unicode: "1f5dc", label: "compression" },
  { unicode: "1f4bd", label: "minidisc" },
  { unicode: "1f4be", label: "floppy disk" },
  { unicode: "1f4bf", label: "optical disc" },
  { unicode: "1f4c0", label: "dvd" },
  { unicode: "1f4fc", label: "videocassette" },
  { unicode: "1f4f7", label: "camera" },
  { unicode: "1f4f8", label: "camera with flash" },
  { unicode: "1f4f9", label: "video camera" },
  { unicode: "1f3a5", label: "movie camera" },
  { unicode: "1f4fd", label: "film projector" },
  { unicode: "1f39e", label: "film frames" },
  { unicode: "1f4de", label: "telephone receiver" },
  { unicode: "260e", label: "black telephone" },
  { unicode: "1f4df", label: "pager" },
  { unicode: "1f4e0", label: "fax machine" },
  { unicode: "1f4fa", label: "television" },
  { unicode: "1f4fb", label: "radio" },
  { unicode: "1f399", label: "studio microphone" },
  { unicode: "1f39a", label: "level slider" },
  { unicode: "1f39b", label: "control knobs" },
  { unicode: "23f1", label: "stopwatch" },
  { unicode: "23f2", label: "timer clock" },
  { unicode: "23f0", label: "alarm clock" },
  { unicode: "1f570", label: "mantlepiece clock" },
  { unicode: "23f3", label: "hourglass with flowing sand" },
  { unicode: "231b", label: "hourglass" },
  { unicode: "1f4e1", label: "satellite antenna" },
  { unicode: "1f50b", label: "battery" },
  { unicode: "1f50c", label: "electric plug" },
  { unicode: "1f4a1", label: "electric light bulb" },
  { unicode: "1f526", label: "electric torch" },
  { unicode: "1f56f", label: "candle" },
  { unicode: "1f5d1", label: "wastebasket" },
  { unicode: "1f6e2", label: "oil drum" },
  { unicode: "1f4b8", label: "money with wings" },
  { unicode: "1f4b5", label: "banknote with dollar sign" },
  { unicode: "1f4b4", label: "banknote with yen sign" },
  { unicode: "1f4b6", label: "banknote with euro sign" },
  { unicode: "1f4b7", label: "banknote with pound sign" },
  { unicode: "1f4b0", label: "money bag" },
  { unicode: "1f4b3", label: "credit card" },
  { unicode: "1f48e", label: "gem stone" },
  { unicode: "2696", label: "scales" },
  { unicode: "1f527", label: "wrench" },
  { unicode: "1f528", label: "hammer" },
  { unicode: "2692", label: "hammer and pick" },
  { unicode: "1f6e0", label: "hammer and wrench" },
  { unicode: "26cf", label: "pick" },
  { unicode: "1f529", label: "nut and bolt" },
  { unicode: "2699", label: "gear" },
  { unicode: "26d3", label: "chains" },
  { unicode: "1f52b", label: "pistol" },
  { unicode: "1f4a3", label: "bomb" },
  { unicode: "1f52a", label: "hocho" },
  { unicode: "1f5e1", label: "dagger knife" },
  { unicode: "2694", label: "crossed swords" },
  { unicode: "1f6e1", label: "shield" },
  { unicode: "1f6ac", label: "smoking symbol" },
  { unicode: "2620", label: "skull and crossbones" },
  { unicode: "26b0", label: "coffin" },
  { unicode: "26b1", label: "funeral urn" },
  { unicode: "1f3fa", label: "amphora" },
  { unicode: "1f52e", label: "crystal ball" },
  { unicode: "1f4ff", label: "prayer beads" },
  { unicode: "1f488", label: "barber pole" },
  { unicode: "2697", label: "alembic" },
  { unicode: "1f52d", label: "telescope" },
  { unicode: "1f52c", label: "microscope" },
  { unicode: "1f573", label: "hole" },
  { unicode: "1f48a", label: "pill" },
  { unicode: "1f489", label: "syringe" },
  { unicode: "1f321", label: "thermometer" },
  { unicode: "1f3f7", label: "label" },
  { unicode: "1f516", label: "bookmark" },
  { unicode: "1f6bd", label: "toilet" },
  { unicode: "1f6bf", label: "shower" },
  { unicode: "1f6c1", label: "bathtub" },
  { unicode: "1f511", label: "key" },
  { unicode: "1f5dd", label: "old key" },
  { unicode: "1f6cb", label: "couch and lamp" },
  { unicode: "1f6cc", label: "sleeping accommodation" },
  { unicode: "1f6cf", label: "bed" },
  { unicode: "1f6aa", label: "door" },
  { unicode: "1f6ce", label: "bellhop bell" },
  { unicode: "1f5bc", label: "frame with picture" },
  { unicode: "1f5fa", label: "world map" },
  { unicode: "26f1", label: "umbrella on ground" },
  { unicode: "1f5ff", label: "moyai" },
  { unicode: "1f6cd", label: "shopping bags" },
  { unicode: "1f388", label: "balloon" },
  { unicode: "1f38f", label: "carp streamer" },
  { unicode: "1f380", label: "ribbon" },
  { unicode: "1f381", label: "wrapped present" },
  { unicode: "1f38a", label: "confetti ball" },
  { unicode: "1f389", label: "party popper" },
  { unicode: "1f38e", label: "japanese dolls" },
  { unicode: "1f390", label: "wind chime" },
  { unicode: "1f38c", label: "crossed flags" },
  { unicode: "1f3ee", label: "izakaya lantern" },
  { unicode: "2709", label: "envelope" },
  { unicode: "1f4e9", label: "envelope with downwards arrow above" },
  { unicode: "1f4e8", label: "incoming envelope" },
  { unicode: "1f4e7", label: "e-mail symbol" },
  { unicode: "1f48c", label: "love letter" },
  { unicode: "1f4ee", label: "postbox" },
  { unicode: "1f4ea", label: "closed mailbox with lowered flag" },
  { unicode: "1f4eb", label: "closed mailbox with raised flag" },
  { unicode: "1f4ec", label: "open mailbox with raised flag" },
  { unicode: "1f4ed", label: "open mailbox with lowered flag" },
  { unicode: "1f4e6", label: "package" },
  { unicode: "1f4ef", label: "postal horn" },
  { unicode: "1f4e5", label: "inbox tray" },
  { unicode: "1f4e4", label: "outbox tray" },
  { unicode: "1f4dc", label: "scroll" },
  { unicode: "1f4c3", label: "page with curl" },
  { unicode: "1f4d1", label: "bookmark tabs" },
  { unicode: "1f4ca", label: "bar chart" },
  { unicode: "1f4c8", label: "chart with upwards trend" },
  { unicode: "1f4c9", label: "chart with downwards trend" },
  { unicode: "1f4c4", label: "page facing up" },
  { unicode: "1f4c5", label: "calendar" },
  { unicode: "1f4c6", label: "tear-off calendar" },
  { unicode: "1f5d3", label: "spiral calendar pad" },
  { unicode: "1f4c7", label: "card index" },
  { unicode: "1f5c3", label: "card file box" },
  { unicode: "1f5f3", label: "ballot box with ballot" },
  { unicode: "1f5c4", label: "file cabinet" },
  { unicode: "1f4cb", label: "clipboard" },
  { unicode: "1f5d2", label: "spiral note pad" },
  { unicode: "1f4c1", label: "file folder" },
  { unicode: "1f4c2", label: "open file folder" },
  { unicode: "1f5c2", label: "card index dividers" },
  { unicode: "1f5de", label: "rolled-up newspaper" },
  { unicode: "1f4f0", label: "newspaper" },
  { unicode: "1f4d3", label: "notebook" },
  { unicode: "1f4d5", label: "closed book" },
  { unicode: "1f4d7", label: "green book" },
  { unicode: "1f4d8", label: "blue book" },
  { unicode: "1f4d9", label: "orange book" },
  { unicode: "1f4d4", label: "notebook with decorative cover" },
  { unicode: "1f4d2", label: "ledger" },
  { unicode: "1f4da", label: "books" },
  { unicode: "1f4d6", label: "open book" },
  { unicode: "1f517", label: "link symbol" },
  { unicode: "1f4ce", label: "paperclip" },
  { unicode: "1f587", label: "linked paperclips" },
  { unicode: "2702", label: "black scissors" },
  { unicode: "1f4d0", label: "triangular ruler" },
  { unicode: "1f4cf", label: "straight ruler" },
  { unicode: "1f4cc", label: "pushpin" },
  { unicode: "1f4cd", label: "round pushpin" },
  { unicode: "1f6a9", label: "triangular flag on post" },
  { unicode: "1f3f3", label: "waving white flag" },
  { unicode: "1f3f4", label: "waving black flag" },
  { unicode: "1f510", label: "closed lock with key" },
  { unicode: "1f512", label: "lock" },
  { unicode: "1f513", label: "open lock" },
  { unicode: "1f50f", label: "lock with ink pen" },
  { unicode: "1f58a", label: "lower left ballpoint pen" },
  { unicode: "1f58b", label: "lower left fountain pen" },
  { unicode: "2712", label: "black nib" },
  { unicode: "1f4dd", label: "memo" },
  { unicode: "270f", label: "pencil" },
  { unicode: "1f58d", label: "lower left crayon" },
  { unicode: "1f58c", label: "lower left paintbrush" },
  { unicode: "1f50d", label: "left-pointing magnifying glass" },
  { unicode: "1f50e", label: "right-pointing magnifying glass" }
];
