export const peopleFaces = [
  { unicode: "1f600", label: "grinning face" },
  { unicode: "1f62c", label: "grimacing face" },
  { unicode: "1f601", label: "grinning face with smiling eyes" },
  { unicode: "1f602", label: "face with tears of joy" },
  { unicode: "1f603", label: "smiling face with open mouth" },
  { unicode: "1f604", label: "smiling face with open mouth and smiling eyes" },
  { unicode: "1f605", label: "smiling face with open mouth and cold sweat" },
  { unicode: "1f606",label: "smiling face with open mouth and tightly-closed eyes" },
  { unicode: "1f607", label: "smiling face with halo" },
  { unicode: "1f609", label: "winking face" },
  { unicode: "1f60a", label: "smiling face with smiling eyes" },
  { unicode: "1f642", label: "slightly smiling face" },
  { unicode: "263a", label: "white smiling face" },
  { unicode: "1f60b", label: "face savouring delicious food" },
  { unicode: "1f60c", label: "relieved face" },
  { unicode: "1f60d", label: "smiling face with heart-shaped eyes" },
  { unicode: "1f618", label: "face throwing a kiss" },
  { unicode: "1f617", label: "kissing face" },
  { unicode: "1f619", label: "kissing face with smiling eyes" },
  { unicode: "1f61a", label: "kissing face with closed eyes" },
  { unicode: "1f61c", label: "face with stuck-out tongue and winking eye" },
  { unicode: "1f61d", label: "face with stuck-out tongue and tightly-closed eyes" },
  { unicode: "1f61b", label: "face with stuck-out tongue" },
  { unicode: "1f60e", label: "smiling face with sunglasses" },
  { unicode: "1f60f", label: "smirking face" },
  { unicode: "1f636", label: "face without mouth" },
  { unicode: "1f610", label: "neutral face" },
  { unicode: "1f611", label: "expressionless face" },
  { unicode: "1f612", label: "unamused face" },
  { unicode: "1f633", label: "flushed face" },
  { unicode: "1f61e", label: "disappointed face" },
  { unicode: "1f61f", label: "worried face" },
  { unicode: "1f620", label: "angry face" },
  { unicode: "1f621", label: "pouting face" },
  { unicode: "1f614", label: "pensive face" },
  { unicode: "1f615", label: "confused face" },
  { unicode: "1f641", label: "slightly frowning face" },
  { unicode: "2639", label: "white frowning face" },
  { unicode: "1f623", label: "persevering face" },
  { unicode: "1f616", label: "confounded face" },
  { unicode: "1f62b", label: "tired face" },
  { unicode: "1f629", label: "weary face" },
  { unicode: "1f624", label: "face with look of triumph" },
  { unicode: "1f62e", label: "face with open mouth" },
  { unicode: "1f631", label: "face screaming in fear" },
  { unicode: "1f628", label: "fearful face" },
  { unicode: "1f630", label: "face with open mouth and cold sweat" },
  { unicode: "1f62f", label: "hushed face" },
  { unicode: "1f626", label: "frowning face with open mouth" },
  { unicode: "1f627", label: "anguished face" },
  { unicode: "1f622", label: "crying face" },
  { unicode: "1f625", label: "disappointed but relieved face" },
  { unicode: "1f62a", label: "sleepy face" },
  { unicode: "1f613", label: "face with cold sweat" },
  { unicode: "1f62d", label: "loudly crying face" },
  { unicode: "1f635", label: "dizzy face" },
  { unicode: "1f632", label: "astonished face" },
  { unicode: "1f637", label: "face with medical mask" },
  { unicode: "1f634", label: "sleeping face" },
  { unicode: "1f4a4", label: "sleeping symbol" },
  { unicode: "1f4a9", label: "pile of poo" },
  { unicode: "1f608", label: "smiling face with horns" },
  { unicode: "1f47f", label: "imp" },
  { unicode: "1f479", label: "japanese ogre" },
  { unicode: "1f47a", label: "japanese goblin" },
  { unicode: "1f480", label: "skull" },
  { unicode: "1f47b", label: "ghost" },
  { unicode: "1f47d", label: "extraterrestrial alien" },
  { unicode: "1f63a", label: "smiling cat face with open mouth" },
  { unicode: "1f638", label: "grinning cat face with smiling eyes" },
  { unicode: "1f639", label: "cat face with tears of joy" },
  { unicode: "1f63b", label: "smiling cat face with heart-shaped eyes" },
  { unicode: "1f63c", label: "cat face with wry smile" },
  { unicode: "1f63d", label: "kissing cat face with closed eyes" },
  { unicode: "1f640", label: "weary cat face" },
  { unicode: "1f63f", label: "crying cat face" },
  { unicode: "1f63e", label: "pouting cat face" },
  { unicode: "1f64c", label: "person raising both hands in celebration" },
  { unicode: "1f44f", label: "clapping hands sign" },
  { unicode: "1f44b", label: "waving hand sign" },
  { unicode: "1f44d", label: "thumbs up sign" },
  { unicode: "1f44e", label: "thumbs down sign" },
  { unicode: "1f44a", label: "fisted hand sign" },
  { unicode: "270a", label: "raised fist" },
  { unicode: "270c", label: "victory hand" },
  { unicode: "1f44c", label: "ok hand sign" },
  { unicode: "270b", label: "raised hand" },
  { unicode: "1f450", label: "open hands sign" },
  { unicode: "1f4aa", label: "flexed biceps" },
  { unicode: "1f64f", label: "person with folded hands" },
  { unicode: "261d", label: "white up pointing index" },
  { unicode: "1f446", label: "white up pointing backhand index" },
  { unicode: "1f447", label: "white down pointing backhand index" },
  { unicode: "1f448", label: "white left pointing backhand index" },
  { unicode: "1f449", label: "white right pointing backhand index" },
  { unicode: "1f595", label: "reversed hand with middle finger extended" },
  { unicode: "1f590", label: "raised hand with fingers splayed" },
  { unicode: "1f596", label: "raised hand with part between middle and ring fingers" },
  { unicode: "270d", label: "writing hand" },
  { unicode: "1f485", label: "nail polish" },
  { unicode: "1f444", label: "mouth" },
  { unicode: "1f445", label: "tongue" },
  { unicode: "1f442", label: "ear" },
  { unicode: "1f443", label: "nose" },
  { unicode: "1f441", label: "eye" },
  { unicode: "1f440", label: "eyes" },
  { unicode: "1f464", label: "bust in silhouette" },
  { unicode: "1f465", label: "busts in silhouette" },
  { unicode: "1f5e3", label: "speaking head in silhouette" },
  { unicode: "1f476", label: "baby" },
  { unicode: "1f466", label: "boy" },
  { unicode: "1f467", label: "girl" },
  { unicode: "1f468", label: "man" },
  { unicode: "1f469", label: "woman" },
  { unicode: "1f471", label: "person with blond hair" },
  { unicode: "1f474", label: "older man" },
  { unicode: "1f475", label: "older woman" },
  { unicode: "1f472", label: "man with gua pi mao" },
  { unicode: "1f473", label: "man with turban" },
  { unicode: "1f46e", label: "police officer" },
  { unicode: "1f477", label: "construction worker" },
  { unicode: "1f482", label: "guardsman" },
  { unicode: "1f575", label: "sleuth or spy" },
  { unicode: "1f385", label: "father christmas" },
  { unicode: "1f47c", label: "baby angel" },
  { unicode: "1f478", label: "princess" },
  { unicode: "1f470", label: "bride with veil" },
  { unicode: "1f6b6", label: "pedestrian" },
  { unicode: "1f3c3", label: "runner" },
  { unicode: "1f483", label: "dancer" },
  { unicode: "1f46f", label: "woman with bunny ears" },
  { unicode: "1f46b", label: "man and woman holding hands" },
  { unicode: "1f46c", label: "two men holding hands" },
  { unicode: "1f46d", label: "two women holding hands" },
  { unicode: "1f647", label: "person bowing deeply" },
  { unicode: "1f481", label: "information desk person" },
  { unicode: "1f645", label: "face with no good gesture" },
  { unicode: "1f646", label: "face with ok gesture" },
  { unicode: "1f64b", label: "happy person raising one hand" },
  { unicode: "1f64e", label: "person with pouting face" },
  { unicode: "1f64d", label: "person frowning" },
  { unicode: "1f487", label: "haircut" },
  { unicode: "1f486", label: "face massage" },
  { unicode: "1f491", label: "couple with heart" },
  { unicode: "1f48f", label: "kiss" },
  { unicode: "1f46a", label: "family" },
  { unicode: "1f45a", label: "womans clothes" },
  { unicode: "1f455", label: "t-shirt" },
  { unicode: "1f456", label: "jeans" },
  { unicode: "1f454", label: "necktie" },
  { unicode: "1f457", label: "dress" },
  { unicode: "1f459", label: "bikini" },
  { unicode: "1f458", label: "kimono" },
  { unicode: "1f484", label: "lipstick" },
  { unicode: "1f48b", label: "kiss mark" },
  { unicode: "1f463", label: "footprints" },
  { unicode: "1f460", label: "high-heeled shoe" },
  { unicode: "1f461", label: "womans sandal" },
  { unicode: "1f462", label: "womans boots" },
  { unicode: "1f45e", label: "mans shoe" },
  { unicode: "1f45f", label: "athletic shoe" },
  { unicode: "1f452", label: "womans hat" },
  { unicode: "1f3a9", label: "top hat" },
  { unicode: "26d1", label: "helmet with white cross" },
  { unicode: "1f393", label: "graduation cap" },
  { unicode: "1f451", label: "crown" },
  { unicode: "1f392", label: "school satchel" },
  { unicode: "1f45d", label: "pouch" },
  { unicode: "1f45b", label: "purse" },
  { unicode: "1f45c", label: "handbag" },
  { unicode: "1f4bc", label: "briefcase" },
  { unicode: "1f453", label: "eyeglasses" },
  { unicode: "1f576", label: "dark sunglasses" },
  { unicode: "1f48d", label: "ring" },
  { unicode: "1f302", label: "closed umbrella" }
];
