export const symbols = [
  { "2764": "heavy black heart" },
  { "1f49b": "yellow heart" },
  { "1f49a": "green heart" },
  { "1f499": "blue heart" },
  { "1f49c": "purple heart" },
  { "1f494": "broken heart" },
  { "2763": "heavy heart exclamation mark ornament" },
  { "1f495": "two hearts" },
  { "1f49e": "revolving hearts" },
  { "1f493": "beating heart" },
  { "1f497": "growing heart" },
  { "1f496": "sparkling heart" },
  { "1f498": "heart with arrow" },
  { "1f49d": "heart with ribbon" },
  { "1f49f": "heart decoration" },
  { "262e": "peace symbol" },
  { "271d": "latin cross" },
  { "262a": "star and crescent" },
  { "1f549": "om symbol" },
  { "2638": "wheel of dharma" },
  { "2721": "star of david" },
  { "1f52f": "six pointed star with middle dot" },
  { "1f54e": "menorah with nine branches" },
  { "262f": "yin yang" },
  { "2626": "orthodox cross" },
  { "1f6d0": "place of worship" },
  { "26ce": "ophiuchus" },
  { "2648": "aries" },
  { "2649": "taurus" },
  { "264a": "gemini" },
  { "264b": "cancer" },
  { "264c": "leo" },
  { "264d": "virgo" },
  { "264e": "libra" },
  { "264f": "scorpius" },
  { "2650": "sagittarius" },
  { "2651": "capricorn" },
  { "2652": "aquarius" },
  { "2653": "pisces" },
  { "1f194": "squared id" },
  { "269b": "atom symbol" },
  { "1f233": "squared cjk unified ideograph-7a7a" },
  { "1f239": "squared cjk unified ideograph-5272" },
  { "2622": "radioactive sign" },
  { "2623": "biohazard sign" },
  { "1f4f4": "mobile phone off" },
  { "1f4f3": "vibration mode" },
  { "1f236": "squared cjk unified ideograph-6709" },
  { "1f21a": "squared cjk unified ideograph-7121" },
  { "1f238": "squared cjk unified ideograph-7533" },
  { "1f23a": "squared cjk unified ideograph-55b6" },
  { "1f237": "squared cjk unified ideograph-6708" },
  { "2734": "eight pointed black star" },
  { "1f19a": "squared vs" },
  { "1f251": "circled ideograph accept" },
  { "1f4ae": "white flower" },
  { "1f250": "circled ideograph advantage" },
  { "3299": "circled ideograph secret" },
  { "3297": "circled ideograph congratulation" },
  { "1f234": "squared cjk unified ideograph-5408" },
  { "1f235": "squared cjk unified ideograph-6e80" },
  { "1f232": "squared cjk unified ideograph-7981" },
  { "1f170": "negative squared latin capital letter a" },
  { "1f171": "negative squared latin capital letter b" },
  { "1f18e": "negative squared ab" },
  { "1f191": "squared cl" },
  { "1f17e": "negative squared latin capital letter o" },
  { "1f198": "squared sos" },
  { "26d4": "no entry" },
  { "1f4db": "name badge" },
  { "1f6ab": "no entry sign" },
  { "274c": "cross mark" },
  { "2b55": "heavy large circle" },
  { "1f4a2": "anger symbol" },
  { "2668": "hot springs" },
  { "1f6b7": "no pedestrians" },
  { "1f6af": "do not litter symbol" },
  { "1f6b3": "no bicycles" },
  { "1f6b1": "non-potable water symbol" },
  { "1f51e": "no one under eighteen symbol" },
  { "1f4f5": "no mobile phones" },
  { "2757": "heavy exclamation mark symbol" },
  { "2755": "white exclamation mark ornament" },
  { "2753": "black question mark ornament" },
  { "2754": "white question mark ornament" },
  { "203c": "double exclamation mark" },
  { "2049": "exclamation question mark" },
  { "1f4af": "hundred points symbol" },
  { "1f505": "low brightness symbol" },
  { "1f506": "high brightness symbol" },
  { "1f531": "trident emblem" },
  { "269c": "fleur-de-lis" },
  { "303d": "part alternation mark" },
  { "26a0": "warning sign" },
  { "1f6b8": "children crossing" },
  { "1f530": "japanese symbol for beginner" },
  { "267b": "black universal recycling symbol" },
  { "1f22f": "squared cjk unified ideograph-6307" },
  { "1f4b9": "chart with upwards trend and yen sign" },
  { "2747": "sparkle" },
  { "2733": "eight spoked asterisk" },
  { "274e": "negative squared cross mark" },
  { "2705": "white heavy check mark" },
  { "1f4a0": "diamond shape with a dot inside" },
  { "1f300": "cyclone" },
  { "27bf": "double curly loop" },
  { "1f310": "globe with meridians" },
  { "24c2": "circled latin capital letter m" },
  { "1f3e7": "automated teller machine" },
  { "1f202": "squared katakana sa" },
  { "1f6c2": "passport control" },
  { "1f6c3": "customs" },
  { "1f6c4": "baggage claim" },
  { "1f6c5": "left luggage" },
  { "267f": "wheelchair symbol" },
  { "1f6ad": "no smoking symbol" },
  { "1f6be": "water closet" },
  { "1f17f": "negative squared latin capital letter p" },
  { "1f6b0": "potable water symbol" },
  { "1f6b9": "mens symbol" },
  { "1f6ba": "womens symbol" },
  { "1f6bc": "baby symbol" },
  { "1f6bb": "restroom" },
  { "1f6ae": "put litter in its place symbol" },
  { "1f3a6": "cinema" },
  { "1f4f6": "antenna with bars" },
  { "1f201": "squared katakana koko" },
  { "1f196": "squared ng" },
  { "1f197": "squared ok" },
  { "1f199": "squared up with exclamation mark" },
  { "1f192": "squared cool" },
  { "1f195": "squared new" },
  { "1f193": "squared free" },
  { "1f51f": "keycap ten" },
  { "1f522": "input symbol for numbers" },
  { "25b6": "black right-pointing triangle" },
  { "23f8": "double vertical bar" },
  { "23ef": "black right-pointing double triangle with double vertical bar" },
  { "23f9": "black square for stop" },
  { "23fa": "black circle for record" },
  { "23ed": "black right-pointing double triangle with vertical bar" },
  { "23ee": "black left-pointing double triangle with vertical bar" },
  { "23e9": "black right-pointing double triangle" },
  { "23ea": "black left-pointing double triangle" },
  { "1f500": "twisted rightwards arrows" },
  { "1f501": "clockwise rightwards and leftwards open circle arrows" },
  {
    "1f502":
      "clockwise rightwards and leftwards open circle arrows with circled one overlay"
  },
  { "25c0": "black left-pointing triangle" },
  { "1f53c": "up-pointing small red triangle" },
  { "1f53d": "down-pointing small red triangle" },
  { "23eb": "black up-pointing double triangle" },
  { "23ec": "black down-pointing double triangle" },
  { "27a1": "black rightwards arrow" },
  { "2b05": "leftwards black arrow" },
  { "2b06": "upwards black arrow" },
  { "2b07": "downwards black arrow" },
  { "2197": "north east arrow" },
  { "2198": "south east arrow" },
  { "2199": "south west arrow" },
  { "2196": "north west arrow" },
  { "2195": "up down arrow" },
  { "2194": "left right arrow" },
  { "1f504": "anticlockwise downwards and upwards open circle arrows" },
  { "21aa": "rightwards arrow with hook" },
  { "21a9": "leftwards arrow with hook" },
  { "2934": "arrow pointing rightwards then curving upwards" },
  { "2935": "arrow pointing rightwards then curving downwards" },
  { "2139": "information source" },
  { "1f524": "input symbol for latin letters" },
  { "1f521": "input symbol for latin small letters" },
  { "1f520": "input symbol for latin capital letters" },
  { "1f523": "input symbol for symbols" },
  { "1f3b5": "musical note" },
  { "1f3b6": "multiple musical notes" },
  { "3030": "wavy dash" },
  { "27b0": "curly loop" },
  { "2714": "heavy check mark" },
  { "1f503": "clockwise downwards and upwards open circle arrows" },
  { "2795": "heavy plus sign" },
  { "2796": "heavy minus sign" },
  { "2797": "heavy division sign" },
  { "2716": "heavy multiplication x" },
  { "1f4b2": "heavy dollar sign" },
  { "1f4b1": "currency exchange" },
  { "00a9": "copyright sign" },
  { "00ae": "registered sign" },
  { "2122": "trade mark sign" },
  { "1f51a": "end with leftwards arrow above" },
  { "1f519": "back with leftwards arrow above" },
  { "1f51b": "on with exclamation mark with left right arrow abo" },
  { "1f51d": "top with upwards arrow above" },
  { "1f51c": "soon with rightwards arrow above" },
  { "2611": "ballot box with check" },
  { "1f518": "radio button" },
  { "26aa": "medium white circle" },
  { "26ab": "medium black circle" },
  { "1f534": "large red circle" },
  { "1f535": "large blue circle" },
  { "1f538": "small orange diamond" },
  { "1f539": "small blue diamond" },
  { "1f536": "large orange diamond" },
  { "1f537": "large blue diamond" },
  { "1f53a": "up-pointing red triangle" },
  { "25aa": "black small square" },
  { "25ab": "white small square" },
  { "2b1b": "black large square" },
  { "2b1c": "white large square" },
  { "1f53b": "down-pointing red triangle" },
  { "25fc": "black medium square" },
  { "25fb": "white medium square" },
  { "25fe": "black medium small square" },
  { "25fd": "white medium small square" },
  { "1f532": "black square button" },
  { "1f533": "white square button" },
  { "1f508": "speaker" },
  { "1f509": "speaker with one sound wave" },
  { "1f50a": "speaker with three sound waves" },
  { "1f507": "speaker with cancellation stroke" },
  { "1f4e3": "cheering megaphone" },
  { "1f4e2": "public address loudspeaker" },
  { "1f514": "bell" },
  { "1f515": "bell with cancellation stroke" },
  { "1f0cf": "playing card black joker" },
  { "1f004": "mahjong tile red dragon" },
  { "2660": "black spade suit" },
  { "2663": "black club suit" },
  { "2665": "black heart suit" },
  { "2666": "black diamond suit" },
  { "1f3b4": "flower playing cards" },
  { "1f4ad": "thought balloon" },
  { "1f5ef": "right anger bubble" },
  { "1f4ac": "speech balloon" },
  { "1f550": "clock face one oclock" },
  { "1f551": "clock face two oclock" },
  { "1f552": "clock face three oclock" },
  { "1f553": "clock face four oclock" },
  { "1f554": "clock face five oclock" },
  { "1f555": "clock face six oclock" },
  { "1f556": "clock face seven oclock" },
  { "1f557": "clock face eight oclock" },
  { "1f558": "clock face nine oclock" },
  { "1f559": "clock face ten oclock" },
  { "1f55a": "clock face eleven oclock" },
  { "1f55b": "clock face twelve oclock" },
  { "1f55c": "clock face one-thirty" },
  { "1f55d": "clock face two-thirty" },
  { "1f55e": "clock face three-thirty" },
  { "1f55f": "clock face four-thirty" },
  { "1f560": "clock face five-thirty" },
  { "1f561": "clock face six-thirty" },
  { "1f562": "clock face seven-thirty" },
  { "1f563": "clock face eight-thirty" },
  { "1f564": "clock face nine-thirty" },
  { "1f565": "clock face ten-thirty" },
  { "1f566": "clock face eleven-thirty" },
  { "1f567": "clock face twelve-thirty" }
];
