export const symbols = [
  { unicode: "2764", label: "heavy black heart" },
  { unicode: "1f49b", label: "yellow heart" },
  { unicode: "1f49a", label: "green heart" },
  { unicode: "1f499", label: "blue heart" },
  { unicode: "1f49c", label: "purple heart" },
  { unicode: "1f494", label: "broken heart" },
  { unicode: "2763", label: "heavy heart exclamation mark ornament" },
  { unicode: "1f495", label: "two hearts" },
  { unicode: "1f49e", label: "revolving hearts" },
  { unicode: "1f493", label: "beating heart" },
  { unicode: "1f497", label: "growing heart" },
  { unicode: "1f496", label: "sparkling heart" },
  { unicode: "1f498", label: "heart with arrow" },
  { unicode: "1f49d", label: "heart with ribbon" },
  { unicode: "1f49f", label: "heart decoration" },
  { unicode: "262e", label: "peace symbol" },
  { unicode: "271d", label: "latin cross" },
  { unicode: "262a", label: "star and crescent" },
  { unicode: "1f549", label: "om symbol" },
  { unicode: "2638", label: "wheel of dharma" },
  { unicode: "2721", label: "star of david" },
  { unicode: "1f52f", label: "six pointed star with middle dot" },
  { unicode: "1f54e", label: "menorah with nine branches" },
  { unicode: "262f", label: "yin yang" },
  { unicode: "2626", label: "orthodox cross" },
  { unicode: "1f6d0", label: "place of worship" },
  { unicode: "26ce", label: "ophiuchus" },
  { unicode: "2648", label: "aries" },
  { unicode: "2649", label: "taurus" },
  { unicode: "264a", label: "gemini" },
  { unicode: "264b", label: "cancer" },
  { unicode: "264c", label: "leo" },
  { unicode: "264d", label: "virgo" },
  { unicode: "264e", label: "libra" },
  { unicode: "264f", label: "scorpius" },
  { unicode: "2650", label: "sagittarius" },
  { unicode: "2651", label: "capricorn" },
  { unicode: "2652", label: "aquarius" },
  { unicode: "2653", label: "pisces" },
  { unicode: "1f194", label: "squared id" },
  { unicode: "269b", label: "atom symbol" },
  { unicode: "1f233", label: "squared cjk unified ideograph-7a7a" },
  { unicode: "1f239", label: "squared cjk unified ideograph-5272" },
  { unicode: "2622", label: "radioactive sign" },
  { unicode: "2623", label: "biohazard sign" },
  { unicode: "1f4f4", label: "mobile phone off" },
  { unicode: "1f4f3", label: "vibration mode" },
  { unicode: "1f236", label: "squared cjk unified ideograph-6709" },
  { unicode: "1f21a", label: "squared cjk unified ideograph-7121" },
  { unicode: "1f238", label: "squared cjk unified ideograph-7533" },
  { unicode: "1f23a", label: "squared cjk unified ideograph-55b6" },
  { unicode: "1f237", label: "squared cjk unified ideograph-6708" },
  { unicode: "2734", label: "eight pointed black star" },
  { unicode: "1f19a", label: "squared vs" },
  { unicode: "1f251", label: "circled ideograph accept" },
  { unicode: "1f4ae", label: "white flower" },
  { unicode: "1f250", label: "circled ideograph advantage" },
  { unicode: "3299", label: "circled ideograph secret" },
  { unicode: "3297", label: "circled ideograph congratulation" },
  { unicode: "1f234", label: "squared cjk unified ideograph-5408" },
  { unicode: "1f235", label: "squared cjk unified ideograph-6e80" },
  { unicode: "1f232", label: "squared cjk unified ideograph-7981" },
  { unicode: "1f170", label: "negative squared latin capital letter a" },
  { unicode: "1f171", label: "negative squared latin capital letter b" },
  { unicode: "1f18e", label: "negative squared ab" },
  { unicode: "1f191", label: "squared cl" },
  { unicode: "1f17e", label: "negative squared latin capital letter o" },
  { unicode: "1f198", label: "squared sos" },
  { unicode: "26d4", label: "no entry" },
  { unicode: "1f4db", label: "name badge" },
  { unicode: "1f6ab", label: "no entry sign" },
  { unicode: "274c", label: "cross mark" },
  { unicode: "2b55", label: "heavy large circle" },
  { unicode: "1f4a2", label: "anger symbol" },
  { unicode: "2668", label: "hot springs" },
  { unicode: "1f6b7", label: "no pedestrians" },
  { unicode: "1f6af", label: "do not litter symbol" },
  { unicode: "1f6b3", label: "no bicycles" },
  { unicode: "1f6b1", label: "non-potable water symbol" },
  { unicode: "1f51e", label: "no one under eighteen symbol" },
  { unicode: "1f4f5", label: "no mobile phones" },
  { unicode: "2757", label: "heavy exclamation mark symbol" },
  { unicode: "2755", label: "white exclamation mark ornament" },
  { unicode: "2753", label: "black question mark ornament" },
  { unicode: "2754", label: "white question mark ornament" },
  { unicode: "203c", label: "double exclamation mark" },
  { unicode: "2049", label: "exclamation question mark" },
  { unicode: "1f4af", label: "hundred points symbol" },
  { unicode: "1f505", label: "low brightness symbol" },
  { unicode: "1f506", label: "high brightness symbol" },
  { unicode: "1f531", label: "trident emblem" },
  { unicode: "269c", label: "fleur-de-lis" },
  { unicode: "303d", label: "part alternation mark" },
  { unicode: "26a0", label: "warning sign" },
  { unicode: "1f6b8", label: "children crossing" },
  { unicode: "1f530", label: "japanese symbol for beginner" },
  { unicode: "267b", label: "black universal recycling symbol" },
  { unicode: "1f22f", label: "squared cjk unified ideograph-6307" },
  { unicode: "1f4b9", label: "chart with upwards trend and yen sign" },
  { unicode: "2747", label: "sparkle" },
  { unicode: "2733", label: "eight spoked asterisk" },
  { unicode: "274e", label: "negative squared cross mark" },
  { unicode: "2705", label: "white heavy check mark" },
  { unicode: "1f4a0", label: "diamond shape with a dot inside" },
  { unicode: "1f300", label: "cyclone" },
  { unicode: "27bf", label: "double curly loop" },
  { unicode: "1f310", label: "globe with meridians" },
  { unicode: "24c2", label: "circled latin capital letter m" },
  { unicode: "1f3e7", label: "automated teller machine" },
  { unicode: "1f202", label: "squared katakana sa" },
  { unicode: "1f6c2", label: "passport control" },
  { unicode: "1f6c3", label: "customs" },
  { unicode: "1f6c4", label: "baggage claim" },
  { unicode: "1f6c5", label: "left luggage" },
  { unicode: "267f", label: "wheelchair symbol" },
  { unicode: "1f6ad", label: "no smoking symbol" },
  { unicode: "1f6be", label: "water closet" },
  { unicode: "1f17f", label: "negative squared latin capital letter p" },
  { unicode: "1f6b0", label: "potable water symbol" },
  { unicode: "1f6b9", label: "mens symbol" },
  { unicode: "1f6ba", label: "womens symbol" },
  { unicode: "1f6bc", label: "baby symbol" },
  { unicode: "1f6bb", label: "restroom" },
  { unicode: "1f6ae", label: "put litter in its place symbol" },
  { unicode: "1f3a6", label: "cinema" },
  { unicode: "1f4f6", label: "antenna with bars" },
  { unicode: "1f201", label: "squared katakana koko" },
  { unicode: "1f196", label: "squared ng" },
  { unicode: "1f197", label: "squared ok" },
  { unicode: "1f199", label: "squared up with exclamation mark" },
  { unicode: "1f192", label: "squared cool" },
  { unicode: "1f195", label: "squared new" },
  { unicode: "1f193", label: "squared free" },
  { unicode: "1f51f", label: "keycap ten" },
  { unicode: "1f522", label: "input symbol for numbers" },
  { unicode: "25b6", label: "black right-pointing triangle" },
  { unicode: "23f8", label: "double vertical bar" },
  {
    unicode: "23ef",
    label: "black right-pointing double triangle with double vertical bar"
  },
  { unicode: "23f9", label: "black square for stop" },
  { unicode: "23fa", label: "black circle for record" },
  {
    unicode: "23ed",
    label: "black right-pointing double triangle with vertical bar"
  },
  {
    unicode: "23ee",
    label: "black left-pointing double triangle with vertical bar"
  },
  { unicode: "23e9", label: "black right-pointing double triangle" },
  { unicode: "23ea", label: "black left-pointing double triangle" },
  { unicode: "1f500", label: "twisted rightwards arrows" },
  {
    unicode: "1f501",
    label: "clockwise rightwards and leftwards open circle arrows"
  },
  {
    unicode: "1f502",
    label:
      "clockwise rightwards and leftwards open circle arrows with circled one overlay"
  },
  { unicode: "25c0", label: "black left-pointing triangle" },
  { unicode: "1f53c", label: "up-pointing small red triangle" },
  { unicode: "1f53d", label: "down-pointing small red triangle" },
  { unicode: "23eb", label: "black up-pointing double triangle" },
  { unicode: "23ec", label: "black down-pointing double triangle" },
  { unicode: "27a1", label: "black rightwards arrow" },
  { unicode: "2b05", label: "leftwards black arrow" },
  { unicode: "2b06", label: "upwards black arrow" },
  { unicode: "2b07", label: "downwards black arrow" },
  { unicode: "2197", label: "north east arrow" },
  { unicode: "2198", label: "south east arrow" },
  { unicode: "2199", label: "south west arrow" },
  { unicode: "2196", label: "north west arrow" },
  { unicode: "2195", label: "up down arrow" },
  { unicode: "2194", label: "left right arrow" },
  {
    unicode: "1f504",
    label: "anticlockwise downwards and upwards open circle arrows"
  },
  { unicode: "21aa", label: "rightwards arrow with hook" },
  { unicode: "21a9", label: "leftwards arrow with hook" },
  { unicode: "2934", label: "arrow pointing rightwards then curving upwards" },
  {
    unicode: "2935",
    label: "arrow pointing rightwards then curving downwards"
  },
  { unicode: "2139", label: "information source" },
  { unicode: "1f524", label: "input symbol for latin letters" },
  { unicode: "1f521", label: "input symbol for latin small letters" },
  { unicode: "1f520", label: "input symbol for latin capital letters" },
  { unicode: "1f523", label: "input symbol for symbols" },
  { unicode: "1f3b5", label: "musical note" },
  { unicode: "1f3b6", label: "multiple musical notes" },
  { unicode: "3030", label: "wavy dash" },
  { unicode: "27b0", label: "curly loop" },
  { unicode: "2714", label: "heavy check mark" },
  {
    unicode: "1f503",
    label: "clockwise downwards and upwards open circle arrows"
  },
  { unicode: "2795", label: "heavy plus sign" },
  { unicode: "2796", label: "heavy minus sign" },
  { unicode: "2797", label: "heavy division sign" },
  { unicode: "2716", label: "heavy multiplication x" },
  { unicode: "1f4b2", label: "heavy dollar sign" },
  { unicode: "1f4b1", label: "currency exchange" },
  { unicode: "a9", label: "copyright sign" },
  { unicode: "ae", label: "registered sign" },
  { unicode: "2122", label: "trade mark sign" },
  { unicode: "1f51a", label: "end with leftwards arrow above" },
  { unicode: "1f519", label: "back with leftwards arrow above" },
  {
    unicode: "1f51b",
    label: "on with exclamation mark with left right arrow abo"
  },
  { unicode: "1f51d", label: "top with upwards arrow above" },
  { unicode: "1f51c", label: "soon with rightwards arrow above" },
  { unicode: "2611", label: "ballot box with check" },
  { unicode: "1f518", label: "radio button" },
  { unicode: "26aa", label: "medium white circle" },
  { unicode: "26ab", label: "medium black circle" },
  { unicode: "1f534", label: "large red circle" },
  { unicode: "1f535", label: "large blue circle" },
  { unicode: "1f538", label: "small orange diamond" },
  { unicode: "1f539", label: "small blue diamond" },
  { unicode: "1f536", label: "large orange diamond" },
  { unicode: "1f537", label: "large blue diamond" },
  { unicode: "1f53a", label: "up-pointing red triangle" },
  { unicode: "25aa", label: "black small square" },
  { unicode: "25ab", label: "white small square" },
  { unicode: "2b1b", label: "black large square" },
  { unicode: "2b1c", label: "white large square" },
  { unicode: "1f53b", label: "down-pointing red triangle" },
  { unicode: "25fc", label: "black medium square" },
  { unicode: "25fb", label: "white medium square" },
  { unicode: "25fe", label: "black medium small square" },
  { unicode: "25fd", label: "white medium small square" },
  { unicode: "1f532", label: "black square button" },
  { unicode: "1f533", label: "white square button" },
  { unicode: "1f508", label: "speaker" },
  { unicode: "1f509", label: "speaker with one sound wave" },
  { unicode: "1f50a", label: "speaker with three sound waves" },
  { unicode: "1f507", label: "speaker with cancellation stroke" },
  { unicode: "1f4e3", label: "cheering megaphone" },
  { unicode: "1f4e2", label: "public address loudspeaker" },
  { unicode: "1f514", label: "bell" },
  { unicode: "1f515", label: "bell with cancellation stroke" },
  { unicode: "1f0cf", label: "playing card black joker" },
  { unicode: "1f004", label: "mahjong tile red dragon" },
  { unicode: "2660", label: "black spade suit" },
  { unicode: "2663", label: "black club suit" },
  { unicode: "2665", label: "black heart suit" },
  { unicode: "2666", label: "black diamond suit" },
  { unicode: "1f3b4", label: "flower playing cards" },
  { unicode: "1f4ad", label: "thought balloon" },
  { unicode: "1f5ef", label: "right anger bubble" },
  { unicode: "1f4ac", label: "speech balloon" },
  { unicode: "1f550", label: "clock face one oclock" },
  { unicode: "1f551", label: "clock face two oclock" },
  { unicode: "1f552", label: "clock face three oclock" },
  { unicode: "1f553", label: "clock face four oclock" },
  { unicode: "1f554", label: "clock face five oclock" },
  { unicode: "1f555", label: "clock face six oclock" },
  { unicode: "1f556", label: "clock face seven oclock" },
  { unicode: "1f557", label: "clock face eight oclock" },
  { unicode: "1f558", label: "clock face nine oclock" },
  { unicode: "1f559", label: "clock face ten oclock" },
  { unicode: "1f55a", label: "clock face eleven oclock" },
  { unicode: "1f55b", label: "clock face twelve oclock" },
  { unicode: "1f55c", label: "clock face one-thirty" },
  { unicode: "1f55d", label: "clock face two-thirty" },
  { unicode: "1f55e", label: "clock face three-thirty" },
  { unicode: "1f55f", label: "clock face four-thirty" },
  { unicode: "1f560", label: "clock face five-thirty" },
  { unicode: "1f561", label: "clock face six-thirty" },
  { unicode: "1f562", label: "clock face seven-thirty" },
  { unicode: "1f563", label: "clock face eight-thirty" },
  { unicode: "1f564", label: "clock face nine-thirty" },
  { unicode: "1f565", label: "clock face ten-thirty" },
  { unicode: "1f566", label: "clock face eleven-thirty" },
  { unicode: "1f567", label: "clock face twelve-thirty" }
];
