export const titleEmojis = [
  { unicode: "1f61c", alt: "face with stuck-out tongue and winking eye" },
  { unicode: "1f602", alt: "face with tears of joy" },
  { unicode: "1f607", alt: "smiling face with halo" },
  { unicode: "1f60b", alt: "face savouring delicious food" },
  { unicode: "1f4a9", alt: "pile of poo" },
  { unicode: "1f624", alt: "face with look of triumph" },
  { unicode: "1f608", alt: "smiling face with horns" },
  { unicode: "1f47d", alt: "extraterrestrial alien" },
  { unicode: "1f60d", alt: "smiling face with heart-shaped eyes" },
  { unicode: "1f31a", alt: "new moon with face" },
  { unicode: "1f525", alt: "fire" },
  { unicode: "1f351", alt: "peach" },
  { unicode: "1f345", alt: "tomato" },
  { unicode: "1f36a", alt: "cookie" },
  { unicode: "1f369", alt: "doughnut" },
  { unicode: "1f3c0", alt: "basketball and hoop" },
  { unicode: "1f52e", alt: "crystal ball" },
  { unicode: "1f4a3", alt: "bomb" },
  { unicode: "1f497", alt: "growing heart" }
];
