export const travelPlaces = [
  { "1f697": "automobile" },
  { "1f695": "taxi" },
  { "1f699": "recreational vehicle" },
  { "1f68c": "bus" },
  { "1f68e": "trolleybus" },
  { "1f3ce": "racing car" },
  { "1f693": "police car" },
  { "1f691": "ambulance" },
  { "1f692": "fire engine" },
  { "1f690": "minibus" },
  { "1f69a": "delivery truck" },
  { "1f69b": "articulated lorry" },
  { "1f69c": "tractor" },
  { "1f3cd": "racing motorcycle" },
  { "1f6b2": "bicycle" },
  { "1f6a8": "police cars revolving light" },
  { "1f694": "oncoming police car" },
  { "1f68d": "oncoming bus" },
  { "1f698": "oncoming automobile" },
  { "1f696": "oncoming taxi" },
  { "1f6a1": "aerial tramway" },
  { "1f6a0": "mountain cableway" },
  { "1f69f": "suspension railway" },
  { "1f683": "railway car" },
  { "1f68b": "tram car" },
  { "1f69d": "monorail" },
  { "1f684": "high-speed train" },
  { "1f685": "high-speed train with bullet nose" },
  { "1f688": "light rail" },
  { "1f69e": "mountain railway" },
  { "1f682": "steam locomotive" },
  { "1f686": "train" },
  { "1f687": "metro" },
  { "1f68a": "tram" },
  { "1f689": "station" },
  { "1f681": "helicopter" },
  { "1f6e9": "small airplane" },
  { "2708": "airplane" },
  { "1f6eb": "airplane departure" },
  { "1f6ec": "airplane arriving" },
  { "26f5": "sailboat" },
  { "1f6e5": "motorboat" },
  { "1f6a4": "speedboat" },
  { "26f4": "ferry" },
  { "1f6f3": "passenger ship" },
  { "1f680": "rocket" },
  { "1f6f0": "satellite" },
  { "1f4ba": "seat" },
  { "2693": "anchor" },
  { "1f6a7": "construction sign" },
  { "26fd": "fuel pump" },
  { "1f68f": "bus stop" },
  { "1f6a6": "vertical traffic light" },
  { "1f6a5": "horizontal traffic light" },
  { "1f3c1": "chequered flag" },
  { "1f6a2": "ship" },
  { "1f3a1": "ferris wheel" },
  { "1f3a2": "roller coaster" },
  { "1f3a0": "carousel horse" },
  { "1f3d7": "building construction" },
  { "1f301": "foggy" },
  { "1f5fc": "tokyo tower" },
  { "1f3ed": "factory" },
  { "26f2": "fountain" },
  { "1f391": "moon viewing ceremony" },
  { "26f0": "mountain" },
  { "1f3d4": "snow capped mountain" },
  { "1f5fb": "mount fuji" },
  { "1f30b": "volcano" },
  { "1f5fe": "silhouette of japan" },
  { "1f3d5": "camping" },
  { "26fa": "tent" },
  { "1f3de": "national park" },
  { "1f6e3": "motorway" },
  { "1f6e4": "railway track" },
  { "1f305": "sunrise" },
  { "1f304": "sunrise over mountains" },
  { "1f3dc": "desert" },
  { "1f3d6": "beach with umbrella" },
  { "1f3dd": "desert island" },
  { "1f307": "sunset over buildings" },
  { "1f306": "cityscape at dusk" },
  { "1f3d9": "cityscape" },
  { "1f303": "night with stars" },
  { "1f309": "bridge at night" },
  { "1f30c": "milky way" },
  { "1f320": "shooting star" },
  { "1f387": "firework sparkler" },
  { "1f386": "fireworks" },
  { "1f308": "rainbow" },
  { "1f3d8": "house buildings" },
  { "1f3f0": "european castle" },
  { "1f3ef": "japanese castle" },
  { "1f3df": "stadium" },
  { "1f5fd": "statue of liberty" },
  { "1f3e0": "house building" },
  { "1f3e1": "house with garden" },
  { "1f3da": "derelict house building" },
  { "1f3e2": "office building" },
  { "1f3ec": "department store" },
  { "1f3e3": "japanese post office" },
  { "1f3e4": "european post office" },
  { "1f3e5": "hospital" },
  { "1f3e6": "bank" },
  { "1f3e8": "hotel" },
  { "1f3ea": "convenience store" },
  { "1f3eb": "school" },
  { "1f3e9": "love hotel" },
  { "1f492": "wedding" },
  { "1f3db": "classical building" },
  { "26ea": "church" },
  { "1f54c": "mosque" },
  { "1f54d": "synagogue" },
  { "1f54b": "kaaba" },
  { "26e9": "shinto shrine" }
];
