export const travelPlaces = [
  { unicode: "1f697", label: "automobile" },
  { unicode: "1f695", label: "taxi" },
  { unicode: "1f699", label: "recreational vehicle" },
  { unicode: "1f68c", label: "bus" },
  { unicode: "1f68e", label: "trolleybus" },
  { unicode: "1f3ce", label: "racing car" },
  { unicode: "1f693", label: "police car" },
  { unicode: "1f691", label: "ambulance" },
  { unicode: "1f692", label: "fire engine" },
  { unicode: "1f690", label: "minibus" },
  { unicode: "1f69a", label: "delivery truck" },
  { unicode: "1f69b", label: "articulated lorry" },
  { unicode: "1f69c", label: "tractor" },
  { unicode: "1f3cd", label: "racing motorcycle" },
  { unicode: "1f6b2", label: "bicycle" },
  { unicode: "1f6a8", label: "police cars revolving light" },
  { unicode: "1f694", label: "oncoming police car" },
  { unicode: "1f68d", label: "oncoming bus" },
  { unicode: "1f698", label: "oncoming automobile" },
  { unicode: "1f696", label: "oncoming taxi" },
  { unicode: "1f6a1", label: "aerial tramway" },
  { unicode: "1f6a0", label: "mountain cableway" },
  { unicode: "1f69f", label: "suspension railway" },
  { unicode: "1f683", label: "railway car" },
  { unicode: "1f68b", label: "tram car" },
  { unicode: "1f69d", label: "monorail" },
  { unicode: "1f684", label: "high-speed train" },
  { unicode: "1f685", label: "high-speed train with bullet nose" },
  { unicode: "1f688", label: "light rail" },
  { unicode: "1f69e", label: "mountain railway" },
  { unicode: "1f682", label: "steam locomotive" },
  { unicode: "1f686", label: "train" },
  { unicode: "1f687", label: "metro" },
  { unicode: "1f68a", label: "tram" },
  { unicode: "1f689", label: "station" },
  { unicode: "1f681", label: "helicopter" },
  { unicode: "1f6e9", label: "small airplane" },
  { unicode: "2708", label: "airplane" },
  { unicode: "1f6eb", label: "airplane departure" },
  { unicode: "1f6ec", label: "airplane arriving" },
  { unicode: "26f5", label: "sailboat" },
  { unicode: "1f6e5", label: "motorboat" },
  { unicode: "1f6a4", label: "speedboat" },
  { unicode: "26f4", label: "ferry" },
  { unicode: "1f6f3", label: "passenger ship" },
  { unicode: "1f680", label: "rocket" },
  { unicode: "1f6f0", label: "satellite" },
  { unicode: "1f4ba", label: "seat" },
  { unicode: "2693", label: "anchor" },
  { unicode: "1f6a7", label: "construction sign" },
  { unicode: "26fd", label: "fuel pump" },
  { unicode: "1f68f", label: "bus stop" },
  { unicode: "1f6a6", label: "vertical traffic light" },
  { unicode: "1f6a5", label: "horizontal traffic light" },
  { unicode: "1f3c1", label: "chequered flag" },
  { unicode: "1f6a2", label: "ship" },
  { unicode: "1f3a1", label: "ferris wheel" },
  { unicode: "1f3a2", label: "roller coaster" },
  { unicode: "1f3a0", label: "carousel horse" },
  { unicode: "1f3d7", label: "building construction" },
  { unicode: "1f301", label: "foggy" },
  { unicode: "1f5fc", label: "tokyo tower" },
  { unicode: "1f3ed", label: "factory" },
  { unicode: "26f2", label: "fountain" },
  { unicode: "1f391", label: "moon viewing ceremony" },
  { unicode: "26f0", label: "mountain" },
  { unicode: "1f3d4", label: "snow capped mountain" },
  { unicode: "1f5fb", label: "mount fuji" },
  { unicode: "1f30b", label: "volcano" },
  { unicode: "1f5fe", label: "silhouette of japan" },
  { unicode: "1f3d5", label: "camping" },
  { unicode: "26fa", label: "tent" },
  { unicode: "1f3de", label: "national park" },
  { unicode: "1f6e3", label: "motorway" },
  { unicode: "1f6e4", label: "railway track" },
  { unicode: "1f305", label: "sunrise" },
  { unicode: "1f304", label: "sunrise over mountains" },
  { unicode: "1f3dc", label: "desert" },
  { unicode: "1f3d6", label: "beach with umbrella" },
  { unicode: "1f3dd", label: "desert island" },
  { unicode: "1f307", label: "sunset over buildings" },
  { unicode: "1f306", label: "cityscape at dusk" },
  { unicode: "1f3d9", label: "cityscape" },
  { unicode: "1f303", label: "night with stars" },
  { unicode: "1f309", label: "bridge at night" },
  { unicode: "1f30c", label: "milky way" },
  { unicode: "1f320", label: "shooting star" },
  { unicode: "1f387", label: "firework sparkler" },
  { unicode: "1f386", label: "fireworks" },
  { unicode: "1f308", label: "rainbow" },
  { unicode: "1f3d8", label: "house buildings" },
  { unicode: "1f3f0", label: "european castle" },
  { unicode: "1f3ef", label: "japanese castle" },
  { unicode: "1f3df", label: "stadium" },
  { unicode: "1f5fd", label: "statue of liberty" },
  { unicode: "1f3e0", label: "house building" },
  { unicode: "1f3e1", label: "house with garden" },
  { unicode: "1f3da", label: "derelict house building" },
  { unicode: "1f3e2", label: "office building" },
  { unicode: "1f3ec", label: "department store" },
  { unicode: "1f3e3", label: "japanese post office" },
  { unicode: "1f3e4", label: "european post office" },
  { unicode: "1f3e5", label: "hospital" },
  { unicode: "1f3e6", label: "bank" },
  { unicode: "1f3e8", label: "hotel" },
  { unicode: "1f3ea", label: "convenience store" },
  { unicode: "1f3eb", label: "school" },
  { unicode: "1f3e9", label: "love hotel" },
  { unicode: "1f492", label: "wedding" },
  { unicode: "1f3db", label: "classical building" },
  { unicode: "26ea", label: "church" },
  { unicode: "1f54c", label: "mosque" },
  { unicode: "1f54d", label: "synagogue" },
  { unicode: "1f54b", label: "kaaba" },
  { unicode: "26e9", label: "shinto shrine" }
];
